<div class="content-header">
    <div class="header-section">  
<h1>
	<img class="pull-right" style="width:9%; margin-top:-27px;height:100px;width:150px"src="<?php echo $this->url->get("/img/bc-chile.png"); ?>" alt="">
		Consultar <strong>Solicitud</strong><br> 
		<small>Sistema de Solicitudes</small>
</h1>     
    </div>
</div>
<div class="row">

  <!-- Messages List -->
        <div class="col-lg-12">
            <!-- Messages List Block -->
            <div class="block">
                <!-- Messages List Title -->
                <div class="block-title">
                    <div class="block-options pull-right">
                        <a href="javascript:void(0)" class="btn btn-alt btn-sm btn-default" data-toggle="tooltip" title="Settings"><i class="fa fa-cog"></i></a>
                    </div>
                    <h2><span class="text-success">En Curso <strong>(4)</strong><span> <span class="text-warning">Pendiente Cliente <strong>(2)</strong><span> <span class="text-danger">Pendiente Proveedor <strong>(2)</strong><span></h2>
                </div>
                <!-- END Messages List Title -->

                <!-- Messages List Content -->
                <div class="table-responsive">
                    <table class="table table-hover table-vcenter">
                        <thead>
                            <tr>
                                <td class="text-center">
                                    <input type="checkbox" id="checkbox-all" name="checkbox-all">
                                </td>
                                <td colspan="3">
                                    <div class="btn-group btn-group-sm">
                                        <a href="javascript:void(0)" class="btn btn-default" data-toggle="tooltip" title="Archive Selected"><i class="fa fa-briefcase"></i></a>
                                        <a href="javascript:void(0)" class="btn btn-default" data-toggle="tooltip" title="Star Selected"><i class="fa fa-star"></i></a>
                                        <a href="javascript:void(0)" class="btn btn-default" data-toggle="tooltip" title="Delete Selected"><i class="fa fa-times"></i></a>
                                    </div>
                                </td>
                                <td class="text-right" colspan="3">
                                    <strong>1-30</strong> de <strong>100</strong>
                                    <div class="btn-group btn-group-sm">
                                        <a href="javascript:void(0)" class="btn btn-sm btn-default"><i class="fa fa-angle-left"></i></a>
                                        <a href="javascript:void(0)" class="btn btn-sm btn-default"><i class="fa fa-angle-right"></i></a>
                                    </div>
                                </td>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- Use the first row as a prototype for your column widths -->
                            <tr>
                                <td class="text-center" style="width: 30px;">
                                    <input type="checkbox" id="checkbox1" name="checkbox1">
                                </td>
                                <td class="text-center" style="width: 30px;">
                                    <a href="javascript:void(0)" class="text-muted msg-fav-btn"><i class="fa fa-star-o"></i></a>
                                </td>
                                <td class="text-center" style="width: 30px;">
                                    <span class="label label-danger">Pendiente</span>
                                </td>
                                <td>
                                    <a href="#modal-info" data-toggle="modal"><strong>Usuario desconfigurado</strong></a>
                                    <span class="text-muted">Usuario no ha podido entrar a....</span>
                                </td>
                                <td class="text-right" style="width: 90px;"><em>Ahora</em></td>
                            </tr>
                            <tr>
                                <td class="text-center">
                                    <input type="checkbox" id="checkbox2" name="checkbox2">
                                </td>
                                <td class="text-center">
                                    <a href="javascript:void(0)" class="text-warning msg-fav-btn"><i class="fa fa-star"></i></a>
                                </td>
                                <td class="text-center">
                                    <span class="label label-danger">Pendiente</span>
                                </td>
                                <td><a href="#modal-info" data-toggle="modal"><strong>Iphone sin Bateria</strong></a>
                                    <span class="text-muted">No puede estar sin su Iphon..</span> 
                                </td>
                                <td class="text-right"><em>hace 2 min</em></td>
                            </tr>
                            <tr>
                                <td class="text-center">
                                    <input type="checkbox" id="checkbox3" name="checkbox3">
                                </td>
                                <td class="text-center">
                                    <a href="javascript:void(0)" class="text-muted msg-fav-btn"><i class="fa fa-star-o"></i></a>
                                </td>
                                <td class="text-center">
                                    <span class="label label-warning">Pendiente</span>
                                </td>
                                <td>
                                    <a href="#modal-info" data-toggle="modal"><strong>Renovacion de Notebook</strong></a>
                                    <span class="text-muted">Devolucion del antiguo pendiente..</span>
                                </td>
                                <td class="text-right"><em>Hace 10 min</em></td>
                            </tr>
                            <tr>
                                <td class="text-center">
                                    <input type="checkbox" id="checkbox4" name="checkbox4">
                                </td>
                                <td class="text-center">
                                    <a href="javascript:void(0)" class="text-muted msg-fav-btn"><i class="fa fa-star-o"></i></a>
                                </td>
                                <td class="text-center">
                                    <span class="label label-success">En Curso</span>
                                </td>
                                <td>
                                    <a href="page_ready_inbox_message.php"><strong>Soporte Tecnico </strong></a>
                                    <span class="text-muted">Necesito un tecnico ahora....</span>
                                </td>
                                <td class="text-right"><em>Hace 30 min</em></td>
                            </tr>
                            <tr>
                                <td class="text-center">
                                    <input type="checkbox" id="checkbox5" name="checkbox5">
                                </td>
                                <td class="text-center">
                                    <a href="javascript:void(0)" class="text-warning msg-fav-btn"><i class="fa fa-star"></i></a>
                                </td>
                                <td class="text-center">
                                    <span class="label label-warning">Pendiente</span>
                                </td>
                                <td>
                                    <a href="#modal-info" data-toggle="modal"><strong>Tarjeta de Identificacion</strong></a>
                                    <span class="text-muted">Renvacion por perdida..</span>
                                </td>
                                <td class="text-right"><em>Hace 40 min</em></td>
                            </tr>
                            <tr>
                                <td class="text-center">
                                    <input type="checkbox" id="checkbox6" name="checkbox6">
                                </td>
                                <td class="text-center">
                                    <a href="javascript:void(0)" class="text-muted msg-fav-btn"><i class="fa fa-star-o"></i></a>
                                </td>
                                <td class="text-center">
                                    <span class="label label-success">En Curso</span>
                                </td>
                                <td>
                                    <a href="#modal-info" data-toggle="modal"><strong>Compra Notebook</strong></a>
                                    <span class="text-muted">Necesita un equipo</span>
                                </td>
                                <td class="text-right"><em>Hace 55 min</em></td>
                            </tr>
                            <tr>
                                <td class="text-center">
                                    <input type="checkbox" id="checkbox7" name="checkbox7">
                                </td>
                                <td class="text-center">
                                    <a href="javascript:void(0)" class="text-warning msg-fav-btn"><i class="fa fa-star"></i></a>
                                </td>
                                <td class="text-center">
                                    <span class="label label-success">En Curso</span>
                                </td>
                                <td>
                                    <a href="page_ready_inbox_message.php"><strong>Interfaz de Comunicacion</strong></a>
                                    <span class="text-muted">Corrupcion en Interfaz de Co..</span>
                                </td>
                                <td class="text-right"><em>Ayer</em></td>
                            </tr>
                            <tr>
                                <td class="text-center">
                                    <input type="checkbox" id="checkbox8" name="checkbox8">
                                </td>
                                <td class="text-center">
                                    <a href="javascript:void(0)" class="text-warning msg-fav-btn"><i class="fa fa-star"></i></a>
                                </td>
                                <td class="text-center">
                                    <span class="label label-success">En Curso</span>
                                </td>
                                <td>
                                    <a href="#modal-info" data-toggle="modal"><strong>Instalacion de S.O</strong></a>
                                    <span class="text-muted">Instalacionde Windows..</span>
                                </td>
                                <td class="text-right"><em>12-12-2015</em></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- END Messages List Content -->
            </div>
            <!-- END Messages List Block -->
        </div>
        <!-- END Messages List -->

            
                
</div>