	<div class="row">
		<div class="col-sm-6">
			<div class="widget-advanced widget-advanced-alt">
				<div class="widget-header text-center" style="background:rgba(14, 32, 49, 0.6) !important;color: white;">
					<h3 class="widget-content-light text-left pull-left animation-pullDown">
						<strong>Solicitudes</strong> en <strong>Tiempo</strong><br>
						<small style="color: white;">Últimos cinco meses</small>
					</h3>
					<div id="dash-widget-chart" class="chart" style="padding: 0px; position: relative">
						<canvas class="flot-base" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 510px; height: 360px" width="510" height="360"></canvas><canvas class="flot-overlay" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 510px; height: 360px" width="510" height="360">
							
						</canvas>
					</div>
				</div>
			
		</div>
	</div>	
		<div class="col-sm-6">
			<div class="row">
				<div class="col-sm-6">
					<a href="page_ready_article.php" class="widget widget-hover-effect1">
						<div class="widget-simple" style="background:rgba(236, 236, 236,0.6) !important;">
							<div class="widget-icon pull-left themed-background-autumn abiertas animation-fadeIn" style="background-color:green !important;">
								<i class="fa fa-file-text"></i>
							</div>
							<h3 class="widget-content text-right animation-pullDown" >
								Solicitudes <strong>Abiertas</strong><br>
								<strong><b>30</b> </strong>
							</h3>
						</div>
					</a>	
				</div>

				<div class="col-sm-6">	
					<a href="page_ready_article.php" class="widget widget-hover-effect1">
						<div class="widget-simple" style="background-color:rgb(236, 236, 236) !important;">
							<div class="widget-icon pull-left themed-background-autumn animation-fadeIn" style="background-color:#CACA08 !important;">
								<i class="fa fa-file-text"></i>
							</div>
							<h3 class="widget-content text-right animation-pullDown">
								Solicitudes <strong>Cerradas</strong><br>
								<strong><b>50</b> </strong>
							</h3>
						</div>
					</a>									
				</div>					

			</div>
		</div>

</div>

<div class="row">
	<div id="placeholder" class="demo-placeholder">
		
	</div>
</div>
