<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
<head>
	<meta charset="utf-8">

	<title><?php print($this->config->appTitle)?></title>

	<meta name="description" content="<?php print($this->config->appTitle)?>">
	<meta name="author" content="<?php print($this->config->appAutor)?>">
	<meta name="robots" content="noindex, nofollow">

	<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

	<!-- Icons -->
	<!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
	<link rel="shortcut icon" href="assets/img/favicon.png">
	<link rel="apple-touch-icon" href="assets/img/icon57.png" sizes="57x57">
	<link rel="apple-touch-icon" href="assets/img/icon72.png" sizes="72x72">
	<link rel="apple-touch-icon" href="assets/img/icon76.png" sizes="76x76">
	<link rel="apple-touch-icon" href="assets/img/icon114.png" sizes="114x114">
	<link rel="apple-touch-icon" href="assets/img/icon120.png" sizes="120x120">
	<link rel="apple-touch-icon" href="assets/img/icon144.png" sizes="144x144">
	<link rel="apple-touch-icon" href="assets/img/icon152.png" sizes="152x152">
	<link rel="apple-touch-icon" href="assets/img/icon180.png" sizes="180x180">
	<!-- END Icons -->

	<!-- Stylesheets -->
	<!-- Bootstrap is included in its original form, unaltered -->
    <?php print($this->tag->stylesheetLink("css/bootstrap.min.css"))?>

	<!-- Related styles of various icon packs and plugins -->
    <?php print($this->tag->stylesheetLink("css/plugins.css"))?>

	<!-- The main stylesheet of this template. All Bootstrap overwrites are defined in here -->
    <?php print($this->tag->stylesheetLink("css/main.css"))?>

	<!-- The themes stylesheet of this template (for using specific theme color in individual elements - must included last) -->
    <?php print($this->tag->stylesheetLink("css/themes.css"))?>

    <!-- tema personalizado para bc -->
    <?php print($this->tag->stylesheetLink("css/bcentral-custom.css"))?>
	<!-- END Stylesheets -->

	<?php
		if(isset($addCss)){
			foreach($addCss as $link){
				print($this->tag->stylesheetLink($link));
			}
		}
	?>
	
	<!-- Modernizr (browser feature detection library) & Respond.js (enables responsive CSS code on browsers that don't support it, eg IE8) -->
	<?php print($this->tag->javascriptInclude("js/vendor/modernizr-respond.min.js"))?>

</head>
<body class="page-loading">
		<div id="page-container" class="style-alt">
	        <!-- Main Container -->
	        <div id="main-container">

	            <header class="navbar navbar-default theme-banco-central ">
	                <!-- Navbar Header -->
		            <div class="navbar-header">
		                <!-- Horizontal Menu Toggle + Alternative Sidebar Toggle Button, Visible only in small screens (< 768px) -->
		                <ul class="nav navbar-nav-custom pull-right visible-xs">
		                    <li>
		                        <a href="javascript:void(0)" data-toggle="collapse" data-target="#horizontal-menu-collapse">Menu</a>
		                    </li>
		                </ul>
		                <!-- END Horizontal Menu Toggle + Alternative Sidebar Toggle Button -->

		            </div>
		            <!-- END Navbar Header -->

		            <div id="horizontal-menu-collapse" class="collapse navbar-collapse">

			            <!-- Alternative Sidebar Toggle Button, Visible only in large screens (> 767px) -->
			            <ul class="nav navbar-nav-custom pull-right hidden-xs">
							<li class="dropdown">
			                    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
			                        <i class="gi gi-user"></i><strong> Alejandro Aguilera</strong> <i class="fa fa-angle-down"></i>
			                    </a>
			                    <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
			                        <li class="dropdown-header text-center">Opciones</li>
			                        <li>
			                            <a href="page_ready_timeline.php">
			                                <i class="fa fa-ban fa-fw pull-right"></i>
			                                Desconectarse
			                            </a>
			                        </li>

			                    </ul>
			                </li>
			            </ul>
		            </div>
	            </header>
	            <!-- END Header -->

	            <!-- Page Content -->
	            <div id="page-content" class="clearfix">
	                <!-- Dashboard Header -->
				    <!-- For an image header add the class 'content-header-media' and an image as in the following example -->
				    <div class="content-header content-header-media">
				        <div class="header-section header-section-bc">
				            <div class="row">
				                <!-- Main Title (hidden on small devices for the statistics to fit) -->
				                <div class="col-md-2 col-lg-1 col-xs-2">
				               		<img src="<?php print($this->url->get("img/bc-chile-icon.png"))?>" style="width: 100%;opacity: 0.8;">
				                </div>
				                <div class="col-md-6 col-lg-6 col-xs-6">
				                    <h1>Bienvenido al <strong>Portal TI</strong><br><small>Banco Central de Chile</small></h1>
				                </div>
				                <!-- END Main Title -->

				                <!-- Top Stats -->

				                <!-- END Top Stats -->
				            </div>
				        </div>
				        <!-- For best results use an image with a resolution of 2560x248 pixels (You can also use a blurred image with ratio 10:1 - eg: 1000x100 pixels - it will adjust and look great!) -->
				        <img src="<?php print($this->url->get("img/background-encabezado2.png"))?>" alt="header image" class="" style="width: 100%;opacity: 0.9;">
				    </div>
				    <!-- END Dashboard Header -->

				    <!-- Widgets Row -->
				    <div class="row">
				    	<div class="col-lg-12">
	                    	<div id="breadcrumbs">
								<span class="  ">
									<i class="fa fa-arrow-right"></i>	
									<span id="textTecnologia"><a href="<?php print($this->url->get('comercio')) ?>">Inicio</a></span>
								</span>
								<span class="  ">
									<i class="fa fa-arrow-right"></i>	
									<span id="textAplicaciones"  >Evaluar</span>
								</span>
	                    	</div>

                    	</div>
				    </div>


				                        <!-- Tickets List -->
                    <div class="tab-pane active" id="tickets-list">
                        <div class="block-content-full">
                            <div class="table-responsive remove-margin-bottom">
                                <table class="table table-striped table-vcenter remove-margin-bottom">
                                    <thead>
                                        <tr>
                                            <th class="text-center">Nº Ticket</th>
                                            <th>Estado</th>
                                            <th>Categoria</th>
                                            <th>Titulo</th>
                                            <th class="text-center">Acción</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td class="text-center">#TCK420</td>
                                            <td><span class="label label-default">CERRADO</span></td>
                                            <td>Cambiar Contraseña</td>
                                            <td>
                                                <a href="#modal-encuesta" data-toggle="modal"><strong>Necesito cambiar contraseña usuario SSO</strong></a><br>
                                                <span class="text-muted">7/03/2016 <strong> 16:40 </strong></span>
                                            </td>
                                            <td class="text-center"> <a href="#modal-encuesta" data-toggle="modal"><strong>Evaluar</strong></a></td>
                                        </tr>
                                        <tr>
                                            <td class="text-center">#TCK420</td>
                                            <td><span class="label label-default">CERRADO</span></td>
                                            <td>Cambiar Contraseña</td>
                                            <td>
                                                <a href="#modal-encuesta" data-toggle="modal"><strong>Necesito cambiar contraseña usuario SSO</strong></a><br>
                                                <span class="text-muted">7/03/2016 <strong> 16:40 </strong></span>
                                            </td>
                                            <td class="text-center"> <a href="#modal-encuesta" data-toggle="modal"><strong>Evaluar</strong></a></td>
                                        </tr>
                                                                                <tr>
                                            <td class="text-center">#TCK420</td>
                                            <td><span class="label label-default">CERRADO</span></td>
                                            <td>Cambiar Contraseña</td>
                                            <td>
                                                <a href="#modal-encuesta" data-toggle="modal"><strong>Necesito cambiar contraseña usuario SSO</strong></a><br>
                                                <span class="text-muted">7/03/2016 <strong> 16:40 </strong></span>
                                            </td>
                                            <td class="text-center"> <a href="#modal-encuesta" data-toggle="modal"><strong>Evaluar</strong></a></td>
                                        </tr>
                                         <tr>
                                            <td class="text-center">#TCK420</td>
                                            <td><span class="label label-default">CERRADO</span></td>
                                            <td>Cambiar Contraseña</td>
                                            <td>
                                                <a href="#modal-encuesta" data-toggle="modal"><strong>Necesito cambiar contraseña usuario SSO</strong></a><br>
                                                <span class="text-muted">7/03/2016 <strong> 16:40 </strong></span>
                                            </td>
                                            <td class="text-center"> <a href="#modal-encuesta" data-toggle="modal"><strong>Evaluar</strong></a></td>
                                        </tr>
                                        
                                    </tbody>
                                </table>
                            </div>
                            <div class="text-center">
                                <ul class="pagination">
                                    <li class="disabled"><a href="javascript:void(0)"><i class="fa fa-chevron-left"></i></a></li>
                                    <li class="active"><a href="javascript:void(0)">1</a></li>
                                    <li><a href="javascript:void(0)">2</a></li>
                                    <li><a href="javascript:void(0)">3</a></li>
                                    <li><a href="javascript:void(0)"><i class="fa fa-chevron-right"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- END Tickets List -->


				</div>


 				<!-- Footer -->
	            <footer class="clearfix">
	                <div class="pull-right">
	                	<a href="http://www.bccentral.cl" >Banco Central de Chile</a>
	            	</div>
		            <div class="pull-left">
		                <span id="year-copy"></span> 2016 &copy; <a href="" target="_blank">Portal TI - BCCH</a>
		            </div>
	            </footer>
	            <!-- END Footer -->
			</div>
		</div>


					<div id="modal-encuesta" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
						<div class="modal-dialog">
							<div class="modal-content">
					            <!-- Updates Title -->
					            <div class="block-title" style=" margin: 0px;">
					                <button type="button" class="close closeModal" data-dismiss="modal" aria-hidden="true">&times;</button>
					                <h2><strong>Encuesta</strong></h2>
					            </div>
					            <!-- END Updates Title -->
					            <div class="modal-body">

									<div class="progress progress-striped active">
										<div id="barra-progreso" class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 10%;"></div>
									</div>	
					            	<!-- Pregunta 1 -->

									<div class="stp-trat"  id="stp-trat-pregunta1">
								
										<h3 class="text-center" style="padding-bottom:50px;">
											¿Cómo considera su desempeño?
										</h3>
										<div class="form-group row text-center">
											<div class="col-lg-12">
												<a href="#" class="widget btn-info stp-trat-btn h" data-next="pregunta2" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
													<div class="widget-simple">
														<img src="<?php echo $this->url->get("/img/icon_feliz.png"); ?>"alt="" height="32px" width="32px">
													</div>
												</a>
											</div>	
											<div class="col-lg-12">
												<a href="#" class="widget btn-info stp-trat-btn" data-next="pregunta2" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
													<div class="widget-simple">
														<img src="<?php echo $this->url->get("/img/icon_normal1.png"); ?>"alt="" height="32px" width="32px">
													</div>
												</a>
											</div>	
											<div class="col-lg-12">
												<a href="#" class="widget btn-info stp-trat-btn" data-next="pregunta2" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
													<div class="widget-simple">
														<img src="<?php echo $this->url->get("/img/icon_triste.png"); ?>"alt="" height="32px" width="32px">
													</div>
												</a>
											</div>													
					                    </div>
										<div class="form-group row text-center" style="margin-top: 25px;width: auto;margin-left: -20px;margin-right: -29px;">	
											<div class="btn-group" style="width: 100%;">
												<a href="#" class="btn btn-primary active" style="width: 33%;border-radius: 0px;">Pregunta 1</a>
												<a href="#" class="btn btn-primary" style="width: 33%;" disabled>Pregunta 2</a>
												<a href="#" class="btn btn-primary" style="width: 33%;border-radius: 0px;" disabled>Pregunta 3</a>
											</div>
					                    </div>                    
									</div>

									<!-- Pregunta 2 -->

									<div class="stp-trat"  id="stp-trat-pregunta2" style="display:none;">
										<h3 class="text-center" style="padding-bottom:50px;">
											¿Cómo considera el desempeño de sus compañeros?	
										</h3>				
										<div class="form-group row text-center">
												<div class="col-lg-12">
													<a href="#" class="widget btn-info stp-trat-btn" data-next="pregunta3" data-stp="" data-val="" data-type="pregunta2" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
														<div class="widget-simple">
															<img src="<?php echo $this->url->get("/img/icon_feliz.png"); ?>"alt="" height="32px" width="32px">
														</div>
													</a>
												</div>														
												<div class="col-lg-12">
													<a href="#" class="widget btn-info stp-trat-btn" data-next="pregunta3" data-stp="" data-val="" data-type="pregunta2" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
														<div class="widget-simple">
															<img src="<?php echo $this->url->get("/img/icon_normal1.png"); ?>"alt="" height="32px" width="32px">
														</div>
													</a>
												</div>	
												<div class="col-lg-12">
													<a href="#" class="widget btn-info stp-trat-btn" data-next="pregunta3" data-stp="" data-val="" data-type="pregunta2" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
														<div class="widget-simple">
															<img src="<?php echo $this->url->get("/img/icon_triste.png"); ?>"alt="" height="32px" width="32px">
														</div>
													</a>
												</div>														
										</div>
										<div class="form-group row text-center" style="margin-top: 25px;width: auto;margin-left: -20px;margin-right: -29px;">	
											<div class="btn-group" style="width: 100%;">
												<a href="#" class="btn btn-primary stp-trat-btn-menu" data-next="pregunta1" style="width: 33%;border-radius: 0px;">Pregunta 1</a>
												<a href="#" class="btn btn-primary active" style="width: 33%;">Pregunta 2</a>
												<a href="#" class="btn btn-primary" style="width: 33%;border-radius: 0px;" disabled>Pregunta 3</a>
											</div>
										</div>															
									</div>	

									<!-- Pregunta 3 -->

									<div class="stp-trat"  id="stp-trat-pregunta3" style="display:none;">
										<h3 class="text-center" style="padding-bottom:50px;">
											¿Cómo considera el desempeño de sus superiores?
										</h3>				
										<div class="form-group row text-center">
											<div class="col-lg-12">
												<a href="#" class="widget btn-info stp-trat-btn" data-next="resultado" data-stp="pregunta3" data-val="OD" data-type="pregunta3" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
													<div class="widget-simple">
														<img src="<?php echo $this->url->get("/img/icon_feliz.png"); ?>"alt="" height="32px" width="32px">
													</div>
												</a>
											</div>												
											<div class="col-lg-12">
												<a href="#" class="widget btn-info stp-trat-btn" data-next="resultado" data-stp="pregunta3" data-val="" data-type="pregunta3" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
													<div class="widget-simple">
														<img src="<?php echo $this->url->get("/img/icon_normal1.png"); ?>"alt="" height="32px" width="32px">
													</div>
												</a>
											</div>												
										</div>	
										<div class="form-group row text-center">
											<div class="col-lg-12">
												<a href="#" class="widget btn-info stp-trat-btn" data-next="resultado" data-stp="pregunta3" data-val="" data-type="pregunta3" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
													<div class="widget-simple">
														<img src="<?php echo $this->url->get("/img/icon_triste.png"); ?>"alt="" height="32px" width="32px">
													</div>
												</a>
											</div>												
										</div>
										<div class="form-group row text-center" style="margin-top: 25px;width: auto;margin-left: -20px;margin-right: -29px;">	
											<div class="btn-group" style="width: 100%;">
												<a href="#" class="btn btn-primary stp-trat-btn-menu" data-next="pregunta1" style="width: 33%;border-radius: 0px;">Pregunta 1</a>
												<a href="#" class="btn btn-primary stp-trat-btn-menu" style="width: 33%;" data-next="pregunta2">Pregunta 2</a>
												<a href="#" class="btn btn-primary active" style="width: 33%;border-radius: 0px;">Pregunta 3</a>
											</div>
										</div>																		
									</div>	

									<!-- Resultado -->		

									<div class="stp-trat"  id="stp-trat-resultado" style="display:none;">
										<div class="form-group row text-center" style="margin-top: -15px;">
											<div class="col-lg-12"  style="margin-top:20%">
												<h2><i class="fa fa-hand-peace-o"></i>¡<strong>Gracias</strong> por responder!</h2> <br>
											</div>
										</div>
									</div>																							
					            </div>



							
					            <div class="modal-footer">
					                <div class="btn-group btn-group-sm pull-right">
					                    <a class="btn btn-sm btn-default pull-right" data-dismiss="modal" href=""> Cerrar</a>
					                </div>
					            </div>
							</div>
						</div>
					</div>



	<!-- Remember to include excanvas for IE8 chart support -->
	<!--[if IE 8]><?php print($this->tag->javascriptInclude("js/helpers/excanvas.min.js"))?><![endif]-->

	<!-- jQuery, Bootstrap.js, jQuery plugins and Custom JS code -->
	<?php print($this->tag->javascriptInclude("js/vendor/jquery-1.11.3.min.js"))?>
	<?php print($this->tag->javascriptInclude("js/vendor/bootstrap.min.js"))?>
	<?php print($this->tag->javascriptInclude("js/plugins.js"))?>

	<script>
		$(document).ready(function() {
		    $("div.bhoechie-tab-menu>div.list-group>a").click(function(e) {
		        e.preventDefault();
		        $(this).siblings('a.active').removeClass("active");
		        $(this).addClass("active");
		        var index = $(this).index();
		        $("div.bhoechie-tab>div.bhoechie-tab-content").removeClass("active");
		        $("div.bhoechie-tab>div.bhoechie-tab-content").eq(index).addClass("active");
		    });
		});
	</script>
	<?php
	if(isset($jsScript) && $jsScript!=null){
	?>
	<script>
	<?php print($jsScript)?>
	</script>
	<?php
		}
	?>		
	<?php
		if(isset($addJs) && $addJs!=null){
			foreach($addJs as $link){
	?>
	<?php print($this->tag->javascriptInclude($link))?>
	<?php
			}
		}
	?>
	<?php
	if(isset($jsPosScrt) && $jsPosScrt!=null){
	?>
	<script>
	<?php print($jsPosScrt)?>
	</script>
	<?php
		}
	?>	
</body>
</html>