<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title><?php print($this->config->appTitle)?></title>

	<meta name="description" content="<?php print($this->config->appTitle)?>">
	<meta name="author" content="<?php print($this->config->appAutor)?>">
	<meta name="robots" content="noindex, nofollow">

	<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

	<!-- Icons -->
	<!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
	<!-- END Icons -->

	<!-- Stylesheets -->
	<!-- Bootstrap is included in its original form, unaltered -->
    <?php print($this->tag->stylesheetLink("css/bootstrap.min.css"))?>

	<!-- Related styles of various icon packs and plugins -->
    <?php print($this->tag->stylesheetLink("css/plugins.css"))?>

	<!-- The main stylesheet of this template. All Bootstrap overwrites are defined in here -->
    <?php print($this->tag->stylesheetLink("css/main.css"))?>

	<!-- The themes stylesheet of this template (for using specific theme color in individual elements - must included last) -->
    <?php print($this->tag->stylesheetLink("css/themes.css"))?>

    <!-- tema personalizado para bc -->
    <?php print($this->tag->stylesheetLink("css/bcentral-custom.css"))?>
	<!-- END Stylesheets -->

	<?php
		if(isset($addCss)){
			foreach($addCss as $link){
				print($this->tag->stylesheetLink($link));
			}
		}
	?>
	
	<!-- Modernizr (browser feature detection library) & Respond.js (enables responsive CSS code on browsers that don't support it, eg IE8) -->
	<?php print($this->tag->javascriptInclude("js/vendor/modernizr-respond.min.js"))?>

</head>
<body class="page-loading">
		<div id="page-container" class="style-alt">
	        <!-- Main Container -->
	        <div id="main-container">

	            <header class="navbar navbar-default theme-banco-central ">
	                <!-- Navbar Header -->
		            <div class="navbar-header">
		                <!-- Horizontal Menu Toggle + Alternative Sidebar Toggle Button, Visible only in small screens (< 768px) -->
		                <ul class="nav navbar-nav-custom pull-right visible-xs">
		                    <li>
		                        <a href="javascript:void(0)" data-toggle="collapse" data-target="#horizontal-menu-collapse">Menu</a>
		                    </li>
		                </ul>
		                <!-- END Horizontal Menu Toggle + Alternative Sidebar Toggle Button -->

		            </div>
		            <!-- END Navbar Header -->

		            <div id="horizontal-menu-collapse" class="collapse navbar-collapse">

			            <!-- Alternative Sidebar Toggle Button, Visible only in large screens (> 767px) -->
			            <ul class="nav navbar-nav-custom pull-right hidden-xs">
							<li class="dropdown">
			                    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
			                        <i class="gi gi-user"></i><strong> Alejandro Aguilera</strong> <i class="fa fa-angle-down"></i>
			                    </a>
			                    <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
			                        <li class="dropdown-header text-center">Opciones</li>
			                        <li>
			                            <a href="page_ready_timeline.php">
			                                <i class="fa fa-ban fa-fw pull-right"></i>
			                                Desconectarse
			                            </a>
			                        </li>

			                    </ul>
			                </li>
			            </ul>
		            </div>
	            </header>
	            <!-- END Header -->

	            <!-- Page Content -->
	            <div id="page-content" class="clearfix" style="padding-bottom: 40px;">
	                <!-- Dashboard Header -->
				    <!-- For an image header add the class 'content-header-media' and an image as in the following example -->
				    <div class="content-header content-header-media">
				        <div class="header-section header-section-bc">
				            <div class="row">
				                <!-- Main Title (hidden on small devices for the statistics to fit) -->
				                <div class="col-md-2 col-lg-1 col-xs-2">
				               		<img src="<?php print($this->url->get("img/bc-chile-icon.png"))?>" style="width: 100%;opacity: 0.8;">
				                </div>
				                <div class="col-md-7 col-lg-7 col-xs-7">
				                    <h1>Bienvenido al <strong><?php print($this->config->appName)?></strong><br><small>Banco Central de Chile</small></h1>
				                </div>
				                <!-- END Main Title -->

				                <!-- Top Stats -->

				                <!-- END Top Stats -->
				            </div>
				        </div>
				        <!-- For best results use an image with a resolution of 2560x248 pixels (You can also use a blurred image with ratio 10:1 - eg: 1000x100 pixels - it will adjust and look great!) -->
				        <img src="<?php print($this->url->get("img/background-encabezado2.png"))?>" alt="header image" class="" style="width: 100%;opacity: 0.9;">
				    </div>
				    <!-- END Dashboard Header -->

				    <!-- Widgets Row -->
				    <div class="row">
				        <div class="col-md-6 ">
				            <!-- Timeline Widget -->
				            <div class="widget ">
				                <div class="widget-extra themed-background-dark">
				                    <div class="widget-options">
				                    </div>
				                    <h3 class="widget-content-light">
				                        Nueva <strong>Solicitud</strong>
				                        <small><a href="page_ready_timeline.php"><strong></strong></a></small>
				                    </h3>
				                </div>
				                <div class="widget-extra " style="padding-right: 0px; padding-left: 0px;">

							        <!-- Working Tabs Content -->
							        <div class="row row-catalogo catalogo-lista-home">
				        				<div class="col-xs-12 text-center">
											<a href="<?php print($this->url->get("comercio/solicitudServicio/tecnologia"))?>" class="widget active widget-hover-effect1 catalogo-menu " style="padding: 0px;" data-val="Aplicaciones de Negocio" data-next="aplicaciones" data-type="segundaVista" >
									            <div class="widget-simple text-center">
									            	<div class="row">
									            		<div class="col-xs-4">
									            			<i class="gi gi-display fa-3x"></i>
											                <h3 class="widget-content" >
											                 <strong>Tecnología</strong><br>
											                </h3>
										                </div>
										                <div class="col-xs-8">
										          			<span>Habilitar accesos mediante configuración de permisos, solución de problemas o recuperar datos.</span>
										          		</div>
									          		</div> 
									            </div>
								        	</a>
										</div>
										<div class="col-xs-12 text-center">
											<a href="<?php print($this->url->get("comercio/solicitudServicio/generales"))?>" class="widget active widget-hover-effect1 catalogo-menu " style="padding: 0px;" data-val="Aplicaciones de Negocio" data-next="aplicaciones" data-type="segundaVista" >
									            <div class="widget-simple text-center">
									            	<div class="row">
									            		<div class="col-xs-4">
									            			<i class="gi gi-bullhorn fa-3x"></i>
											                <h3 class="widget-content " >
											                 <strong>Servicios Generales</strong><br>
											                </h3>
										                </div>
										                <div class="col-xs-8">
										          			<span>Habilitar accesos mediante configuración de permisos, solución de problemas o recuperar datos.</span>
										          		</div>
									          		</div> 
									            </div>
								        	</a>
										</div>
										<div class="col-xs-12 text-center">
											<a href="<?php print($this->url->get("comercio/solicitudServicio/otros"))?>" class="widget active widget-hover-effect1 catalogo-menu " style="padding: 0px;" data-val="Aplicaciones de Negocio" data-next="aplicaciones" data-type="segundaVista" >
									            <div class="widget-simple text-center">
									            	<div class="row">
									            		<div class="col-xs-4">
									            			<i class="gi gi-group fa-3x"></i>
											                <h3 class="widget-content" >
											                 <strong>Otros Servicios</strong><br>
											                </h3>
										                </div>
										                <div class="col-xs-8">
										          			<span>Habilitar accesos mediante configuración de permisos, solución de problemas o recuperar datos.</span>
										          		</div>
									          		</div> 
									            </div>
								        	</a>
										</div>
									</div>	
						        </div>
							        <!-- END Working Tabs Content -->

							</div>
			                <!-- Timeline Widget -->
				            <div class="widget-eval">	
					            <a href="<?php print($this->url->get('comercio/conocimiento')) ?>" class="widget widget-hover-effect1" >
					                <div class="widget-simple widget-home-custom">
					                    <div class="pull-left icon-wg">
					                       <i class="hi hi-search"></i>
					                    </div>
					                    <h5 class="widget-content text-right animation-pullDown  widget-simple-bc" style="font-size: 25px;">
					                        Procedimientos, Formularios e Instructivos  <strong></strong><br>
					                        <small class="widget-simple-bc-leyend">Busca documentos </small>
					                    </h5>
					                </div>
					            </a>
				            </div>
				            <!-- END Timeline Widget -->
				            <!-- END Timeline Widget -->
				        </div>

				        <div class="col-md-6">
				            <!-- Your Plan Widget -->
				            <div class="widget">
				                <div class="widget-extra themed-background-dark">
				                    <h3 class="widget-content-light">
				                       <strong>Consultar</strong> Solicitud 
				                        <small><a href="page_ready_pricing_tables.php"><strong></strong></a></small>
				                        <small>Ultimos tickets</small>
				                       
				                    </h3>

				                </div>
				                <div class="widget-extra-full">
				                    <div class="row ">
									                                            <!-- Tickets List -->
					                    <div class="tab-pane active" id="tickets-list">
					                        <div class="block-content-full">
					                            <div class="table-responsive remove-margin-bottom">
					                                <table class="table table-bc table-striped table-vcenter remove-margin-bottom">
					                                    <thead>
					                                        <tr>
					                                            <th class="">ID</th>
					                                            <th>Estado</th>
					                                            <th>Categoria</th>
					                                            <th> Acción</th>
					                                        </tr>
					                                    </thead>
					                                    <tbody>
					                                        <tr>
					                                            <td class="text-center"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK420</a></td>
					                                            <td><span class="label label-danger">PENDIENTE</span></td>
					                                            <td>Cambiar Contraseña</td>
					                                            <td></td>
					                                        </tr>
					                                        <tr>
					                                            <td class="text-center"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK424</a></td>
					                                            <td><span class="label label-default">CERRADO</span></td>
					                                            <td>Comunicaciones y mensajeria</td>
					                                            <td><button style="width:100%" type="button" class="btn  btn-small btn-bc">Evaluar</button></td>
					                                        </tr>
					                                        <tr>
					                                            <td class="text-center"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK426</a></td>
					                                            <td><span class="label label-success">EN CURSO</span></td>
					                                            <td>Insalar Configurar</td>
					                                            <td></td>
					                                        </tr>
					                                        <tr>
					                                            <td class="text-center"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK429</a></td>
					                                            <td><span class="label label-default">CERRADO</span></td>
					                                            <td>Solucionar Problema</td>
					                                            <td><button style="width:100%" type="button" class="btn  btn-small btn-bc">Evaluar</button></td>
					                                        </tr>
					                                        <tr>
					                                            <td class="text-center"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK200</a></td>
					                                            <td><span class="label label-success">EN CURSO</span></td>
					                                            <td>Solucionar Problema</td>
					                                            <td></td>
					                                        </tr>
					                                        <tr>
					                                            <td class="text-center"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK425</a></td>
					                                            <td><span class="label label-success">EN CURSO</span></td>
					                                            <td>Solucionar Problema</td>
					                                            <td></td>
					                                        </tr>
					                                        <tr>
					                                            <td class="text-center"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK425</a></td>
					                                            <td><span class="label label-success">EN CURSO</span></td>
					                                            <td>Solucionar Problema</td>
					                                            <td></td>
					                                        </tr>
					                                        <tr>
					                                            <td class="text-center"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK425</a></td>
					                                            <td><span class="label label-default">CERRADO</span></td>
					                                            <td>Solucionar Problema</td>
					                                            <td><button style="width:100%" type="button" class="btn  btn-small btn-bc">Evaluar</button></td>
					                                        </tr>
					                                        <tr>
					                                            <td class="text-center"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK425</a></td>
					                                            <td><span class="label label-default">CERRADO</span></td>
					                                            <td>Solucionar Problema</td>
					                                            <td><button style="width:100%" type="button" class="btn  btn-small btn-bc">Evaluar</button></td>
					                                        </tr>
					                                    </tbody>
					                                </table>
					                                <div class="col-md-12 text-center" style="margin-bottom: 6px;">
					                                	<a style="font-size: 16px;" href="<?php print($this->url->get('solicitudes')) ?>"> Ver todos ...</a>
					                                </div>
					                            </div>
					                            <div class="text-center col-xs-12">
					                            <br>
					                            	<!--
					                            	<div class="row">
					                            		<div class="col-xs-6">
															 <input type="text" id="id" name="id" class="form-control" placeholder="Nº Ticket">
														</div>
														<div class="col-xs-6">
															<a href="<?php print($this->url->get('ticket')) ?>" style="width:100%" type="button" class="btn btn-bc">Buscar Ticket</a>
														</div>
													</div>
													-->
													<?php echo $this->tag->form("comercio/ticket"); ?>
														 <div class="row">
						                            		<div class="col-xs-6">
																 <input type="text" id="id" name="id" class="form-control" placeholder="Nº Ticket">
															</div>
															<div class="col-xs-6">
																<input type="submit" value="Buscar Ticket" style="width:100%" class="btn btn-bc">
															</div>
														</div>
													</form>
					                            </div>
					                        </div>
					                    </div>
					                    <!-- END Tickets List -->
				                    </div>
				                </div>
				            </div>
				            <!-- END Your Plan Widget -->



				            <!-- Your Plan Widget -->

				            <!-- END Your Plan Widget -->

				  

				        </div>

				    </div>
				    <!-- END Widgets Row -->


	            </div>
	            <!-- END Page Content -->

	            <!-- Footer -->
	            <footer class="clearfix">
		            	
		                <div class="pull-right" >
		                	<a href="http://www.bccentral.cl" >Banco Central de Chile</a>
		            	</div>
			            <div class="pull-left">
			                <span id="year-copy"></span> 2016 &copy; <a href="" target="_blank"><?php print($this->config->appName)?></a>
			            </div>
			            <div class="center-footer">Mesa de ayuda: <i class="gi gi-earphone"></i> (56 2) 670 2000 </div>
	            </footer>
	            <!-- END Footer -->
	        </div>
       		<!-- END Main Container -->

			<!-- Scroll to top link, initialized in js/app.js - scrollToTop() -->
			<a href="#" id="to-top"><i class="fa fa-angle-double-up"></i></a>
		</div>
    	<!-- END Page Container -->



	<!-- Remember to include excanvas for IE8 chart support -->
	<!--[if IE 8]><?php print($this->tag->javascriptInclude("js/helpers/excanvas.min.js"))?><![endif]-->

	<!-- jQuery, Bootstrap.js, jQuery plugins and Custom JS code -->
	<?php print($this->tag->javascriptInclude("js/vendor/jquery-1.11.3.min.js"))?>
	<?php print($this->tag->javascriptInclude("js/vendor/bootstrap.min.js"))?>
	<?php print($this->tag->javascriptInclude("js/plugins.js"))?>
	<?php print($this->tag->javascriptInclude("js/mifaces.js"))?>

	<script>
		$(document).ready(function() {
		    $("div.bhoechie-tab-menu>div.list-group>a").click(function(e) {
		        e.preventDefault();
		        $(this).siblings('a.active').removeClass("active");
		        $(this).addClass("active");
		        var index = $(this).index();
		        $("div.bhoechie-tab>div.bhoechie-tab-content").removeClass("active");
		        $("div.bhoechie-tab>div.bhoechie-tab-content").eq(index).addClass("active");
		    });
		});
	</script>
	<?php
	if(isset($jsScript) && $jsScript!=null){
	?>
	<script>
	<?php print($jsScript)?>
	</script>
	<?php
		}
	?>		
	<?php
		if(isset($addJs) && $addJs!=null){
			foreach($addJs as $link){
	?>
	<?php print($this->tag->javascriptInclude($link))?>
	<?php
			}
		}
	?>
	<?php
	if(isset($jsPosScrt) && $jsPosScrt!=null){
	?>
	<script>
	<?php print($jsPosScrt)?>
	</script>
	<?php
		}
	?>	
</body>
</html>