<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
		<meta charset="utf-8">

		<title><?php print($this->config->appTitle)?></title>

		<meta name="description" content="<?php print($this->config->appTitle)?>">
		<meta name="author" content="<?php print($this->config->appAutor)?>">
		<meta name="robots" content="noindex, nofollow">

		<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

		<!-- Icons -->
		<!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
		<link rel="shortcut icon" href="assets/img/favicon.png">
		<link rel="apple-touch-icon" href="assets/img/icon57.png" sizes="57x57">
		<link rel="apple-touch-icon" href="assets/img/icon72.png" sizes="72x72">
		<link rel="apple-touch-icon" href="assets/img/icon76.png" sizes="76x76">
		<link rel="apple-touch-icon" href="assets/img/icon114.png" sizes="114x114">
		<link rel="apple-touch-icon" href="assets/img/icon120.png" sizes="120x120">
		<link rel="apple-touch-icon" href="assets/img/icon144.png" sizes="144x144">
		<link rel="apple-touch-icon" href="assets/img/icon152.png" sizes="152x152">
		<link rel="apple-touch-icon" href="assets/img/icon180.png" sizes="180x180">
		<!-- END Icons -->

		<!-- Stylesheets -->
		<!-- Bootstrap is included in its original form, unaltered -->
        <?php print($this->tag->stylesheetLink("css/bootstrap.min.css"))?>

		<!-- Related styles of various icon packs and plugins -->
        <?php print($this->tag->stylesheetLink("css/plugins.css"))?>

		<!-- The main stylesheet of this template. All Bootstrap overwrites are defined in here -->
        <?php print($this->tag->stylesheetLink("css/main.css"))?>

		<!-- The themes stylesheet of this template (for using specific theme color in individual elements - must included last) -->
        <?php print($this->tag->stylesheetLink("css/themes.css"))?>
		<!-- END Stylesheets -->

		<?php
			if(isset($addCss)){
				foreach($addCss as $link){
					print($this->tag->stylesheetLink($link));
				}
			}
		?>
		
		<!-- Modernizr (browser feature detection library) & Respond.js (enables responsive CSS code on browsers that don't support it, eg IE8) -->
		<?php print($this->tag->javascriptInclude("js/vendor/modernizr-respond.min.js"))?>

		<style>
			.icon-feliz {
			    background-image: url("img/icon_feliz.png");
			    background-position: center center;
			}
			
#stp-trat-3.form-horizontal .form-group {
    margin-left: 0px;
    margin-right: 0px;
}
.widget-simple .widget-pregunta{
	margin: 1px 0px;
    font-size: 18px;											
}
.style-alt .widget, .style-alt .task-list li{
	background-color: #5bc0de;
}
.h:hover{
	background-color: #46b8da;
}

.navbar-nav-custom .widget{
	background:transparent !important;
	max-height: 137px;
	color:white;
}

.navbar-nav-custom .active{
	background:rgba(205, 210, 5, 0.62) !important;
}

.navbar-nav-custom a{
	margin-bottom: 0px;
}

.navbar-nav-custom > li i {
    font-size: 30px;
}

    

#lista-solicitudes .widget{
    max-width: 24em;
    min-height: 10em;
    margin: auto;
    margin-bottom: 30px;   
    color:white;    
    padding-bottom: 20px;
}
#lista-solicitudes .block-title{
    color:#394263;
}
.en-curso{
    background-color: #5FCA0A !important;
	border: #5FCA0A !important;
}

.pendiente-cliente{
    background-color: #EAC50D !important;
	border: #EAC50D !important;
}    

.pendiente-proveedor{
    background-color: #F92626 !important;
	border: #F92626 !important;
}    

header {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    padding: 25px 0;
    color: #ffffff;
    background: url('../img/template/ie8_opacity_dark_20.png');
    background: rgba(0, 0, 0, 0.2);
    z-index: 1000;
    -webkit-transition: all ease-out 0.25s;
    transition: all ease-out 0.25s;
}

header.header-scroll {
    padding: 10px 0;
    background: url('../img/template/ie8_opacity_dark_60.png');
    background: rgba(0, 0, 0, 0.6);
}

header.header-scroll:hover {
    background: rgba(0, 0, 0, 0.8);
}
#page-content{
    margin-top: 100px;
}


</style>		
	</head>
	<body>
		<img src="<?php print($this->url->get("img/disabilityanswerdesk_hero.png"))?>" alt="Login Full Background" class="full-bg">
        <!-- Page Wrapper -->
        <!-- In the PHP version you can set the following options from inc/config file -->
        <!--
            Available classes:

            'page-loading'      enables page preloader
        -->
        <div id="page-wrapper">
            <!-- Preloader -->
            <!-- Used only if page preloader is enabled from inc/config (PHP version) or the class 'page-loading' is added in #page-wrapper element (HTML version) -->
            <div class="preloader themed-background">
                <h1 class="push-top-bottom text-light text-center"><?php print($this->config->appName)?></h1>
                <div class="inner">
                    <h3 class="text-light visible-lt-ie9 visible-lt-ie10"><strong>Cargando..</strong></h3>
                    <div class="preloader-spinner hidden-lt-ie9 hidden-lt-ie10"></div>
                </div>
            </div>
            <!-- END Preloader -->

            <div id="page-container" class="header-fixed-top sidebar-no-animations">
			
			
				<!-- Main Container -->
				<div id="main-container">

            <header class="navbar navbar-default navbar-fixed-top" style="background: rgba(0,0,0,0.6);">
                                <!-- Left Header Navigation -->
                <ul class="nav navbar-nav-custom">
                    <!-- Main Sidebar Toggle Button -->
                    <li>
                            <img src="<?php print($this->url->get("img/bc-chile-fixed.png"))?>" style="height:130px;"/>
                    </li>
                </ul>

                <!-- Right Header Navigation -->
                <ul class="nav navbar-nav-custom pull-right">
					<li>
						<a  href="<?php print($this->url->get('comercio')) ?>" data-toggle="modal" style="color:white"class="widget <?php print($menuSel == 'dashboard'?'active':'') ?> widget-hover-effect1">
							<div class="widget-simple text-center">
								<div class="widget-icon themed-background-autumn animation-fadeIn text-center" style="margin: 0 45px; background-color:#B3B0A1 !important;">
									<i class="fa fa-tachometer"></i>
								</div>
								<h3 class="widget-content text-center animation-pullDown">
								 <strong>Dashboard</strong><br>
								</h3>
							</div>
						</a>          					
					</li>
                    <li>				
						<a  href="#modal-create" data-toggle="modal" class="widget <?php print($menuSel == 'nuevaSol'?'active':'') ?> widget-hover-effect1">
							<div class="widget-simple text-center">
								<div class="widget-icon themed-background-autumn animation-fadeIn text-center" style="margin: 0 45px; background-color:#EAC50D !important;">
									<i class="fa fa-plus-circle"></i>
								</div>
								<h3 class="widget-content text-center animation-pullDown" style="color:#ffffff;">
								Nueva <strong>Solicitud</strong><br>
								</h3>
							</div>
						</a>    				
					</li>
					<li>
					        <a href="<?php print($this->url->get('comercio/consultar')) ?>" class="widget <?php print($menuSel == 'consultarSol'?'active':'') ?> widget-hover-effect1" style="background-color:#394263" >
					            <div class="widget-simple text-center">
					                <div class="widget-icon themed-background-autumn animation-fadeIn text-center" style="margin: 0 45px; background-color:#35961C !important;">
					                    <i class="fa fa-search"></i>
					                </div>
					                <h3 class="widget-content text-center animation-pullDown" style="color:#ffffff;">
					                    Consultar <strong>Solicitud</strong><br>
					                </h3>
					            </div>
					        </a> 
					</li>				
                    <li>
						<a href="<?php print($this->url->get('comercio/evaluar')) ?>" class="widget <?php print($menuSel == 'evaluarSol'?'active':'') ?> widget-hover-effect1" style="background-color:#394263;" >
							<div class="widget-simple text-center">
								<div class="widget-icon themed-background-autumn animation-fadeIn text-center" style="margin: 0 45px;">
								<i class="fa fa-check"></i>
								</div>
								<h3 class="widget-content text-center animation-pullDown" style="color:#ffffff;">
									Evaluar <strong>Servicio</strong><br>
								</h3>
							</div>
						</a>         
                    </li>									
                    <!-- Alternative Sidebar Toggle Button -->
                    <li>
						<a href="javascript:void(0)" class="widget <?php print($menuSel == 'formularioIns'?'active':'') ?> widget-hover-effect1" style="background-color:#394263" >
							<div class="widget-simple text-center">
								<div class="widget-icon themed-background-autumn animation-fadeIn text-center" style="background-color:#8A6D3B !important; ">
									<i class="fa fa-file-text"></i>
								</div>
								<h3 class="widget-content text-center animation-pullDown" style="color:#ffffff;">
									Formularios <strong>Instructivos</strong><br>
								</h3>
							</div>
						</a>         
                    </li>

                    <!-- END Alternative Sidebar Toggle Button -->
                    <!-- END User Dropdown -->
                </ul>
                <!-- END Right Header Navigation -->
                            </header>
				
	
					<!-- Page content -->
					<div id="page-content">
					<?php if(isset($pcView) && $pcView!=null) 
							echo $this->view->render($pcView,array('pcData'=>$pcData));
					?>
					</div>
                    <!-- END Page Content -->

                    <!-- Footer -->
                    <footer class="clearfix">
                        <div class="pull-right">
                            Propiedad de <?php print($this->config->appAutor)?> <i class="fa fa-heart text-danger"></i> by <a href="<?php print($this->config->appAutorLink)?>" target="_blank"><?php print($this->config->appAutor)?></a>
                        </div>
                        <div class="pull-left">
                            <span id="year-copy"></span> &copy; <a href="<?php print($this->config->appAutorLink)?>" target="_blank"><?php print($this->config->appAutor)?></a>
                        </div>
                    </footer>
                    <!-- END Footer -->

                <!-- Large Modal -->
                <div id="modal-create" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div  class="modal-header">
                            	<div id="breadcrumbs">
                            		<span id="textInicio"><strong>Inicio</strong></span>
                            		<a id="bcInicio" href="javascript:void(0)" class="nsMenu nsBoton hidden" data-next="inicial"><strong>Inicio</strong></a> 
									<span class="nsBoton-tecnologia nsMenu hidden">
										<i class="fa fa-arrow-right"></i>	
										<span id="textTecnologia">Tecnología</span>
									</span>
									<span class="nsBoton-aplicaciones nsMenu hidden">
										<i class="fa fa-arrow-right"></i>	
										<span id="textAplicaciones">Aplicaciones de Negocio</span>
									</span>
									<span class="nsBoton-form-solicitudes nsMenu hidden">
										<i class="fa fa-arrow-right"></i>	
										<span id="textFormSolicitudes"></span>
									</span>									
                            	</div>
                            	<div id="modal_header_1">
	                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	                                <h1 class="modal-title_1"><i class="fa fa-plus-circle"> </i> Nueva <strong>Solicitud</strong></h1>
                            	</div>
                            </div>
							<div id="modalBodyCreate" class="modal-body" style="overflow: hidden; width: auto;">
								<div id="msgCampos" class="alert alert-danger" style="display:none;"> Se deben rellenar todos los campos.</div>
								<h4><div class="block-title alert alert-warning" id="infoTitle">Seleccione tipo de solicitud</div></h4>
								<!--Primera Vista-->
								<div class="row strap nsBoton-inicial">
									<div class="col-md-6 text-center">
										<a href="javascript:void(0)" class="widget active widget-hover-effect1 nsBoton" data-val="Tecnología" data-next="tecnologia" data-type="primeraVista" style="padding-top:20px; border-radius: 20px; background-color: rgba(205, 210, 5, 0.62); color:#394263;"><i class="fa fa-desktop fa-5x" ></i>
								            <div class="widget-simple text-center">
								                <h3 class="widget-content text-center animation-pullDown">
								                 <strong>Tecnología</strong><br>
								                </h3>
								                <strong>Solicitudes relacionadas a tecnología e información.</strong>
								            </div>
							        	</a>
									</div>
									<div class="col-md-6 text-center">
										<a href="javascript:void(0)" class="widget active widget-hover-effect1 nsBoton" data-val="Servicios Generales" data-type="primeraVista" data-next="form-solicitudes"style="padding-top:20px; border-radius: 20px; background-color: rgba(205, 210, 5, 0.62); color:#394263;"><i class="fa fa-bullhorn fa-5x"></i>
								            <div class="widget-simple text-center">
								                <h3 class="widget-content text-center animation-pullDown">
								                 <strong>Servicios Generales</strong><br>
								                </h3>
								                <strong>Solicitudes de índole general.</strong>
								            </div>
							        	</a>
									</div>	
								</div>

								<!-- Segunda Vista-->

								<div class="row strap nsBoton-tecnologia hidden">
									<div class="col-md-3 text-center ">
										<a href="javascript:void(0)" class="widget active widget-hover-effect1 nsBoton" data-val="Aplicaciones de Negocio" data-next="aplicaciones" data-type="segundaVista" style="padding-top:20px; border-radius: 20px; background-color: rgba(205, 210, 5, 0.62); color:#394263;"><i class="fa fa-suitcase fa-5x"></i>
								            <div class="widget-simple text-center">
								                <h3 class="widget-content text-center animation-pullDown" style="height: 40px !important;">
								                 <strong>Aplicaciones de Negocio</strong><br>
								                </h3>
								          		<strong>Habilitar accesos mediante configuración de permisos, solución de problemas o recuperar datos.</strong>      
								            </div>
							        	</a>
									</div>	
									<div class="col-md-3 text-center">
										<a href="javascript:void(0)" class="widget active widget-hover-effect1 nsBoton" data-next="form-solicitudes" data-val="Comunicaciones y Mensajería" data-type="segundaVista" style="padding-top:20px; border-radius: 20px; background-color: rgba(205, 210, 5, 0.62); color:#394263; min-height:269px;"><i class="fa fa-commenting-o fa-5x"></i>
								            <div class="widget-simple text-center">
								                <h3 class="widget-content text-center animation-pullDown" style="height: 40px !important;">
								                 <strong>Comunicaciones y Mensajería</strong><br>
								                </h3>
								                <strong>Habilitar accesos a redes wifi, telefonía Lync o solución de problemas comunicacionales.</strong>
								            </div>
							        	</a>
									</div>	
									<div class="col-md-3 text-center">
										<a href="javascript:void(0)" class="widget active widget-hover-effect1 nsBoton" data-next="form-solicitudes" data-val="Correo Electrónico y Calendarios" data-type="segundaVista" style="padding-top:20px; border-radius: 20px; background-color: rgba(205, 210, 5, 0.62); color:#394263;"><i class="fa fa-envelope fa-5x"></i>
								            <div class="widget-simple text-center">
								                <h3 class="widget-content text-center animation-pullDown" style="height: 40px !important;">
								                 <strong>Correo Electrónico y Calendarios</strong><br>
								                </h3>
								                <strong>Recuperar buzón de mensajes, habilitar correo encriptado o solución de problemas relacionados.</strong>
								            </div>
							        	</a>
									</div>											
									<div class="col-md-3 text-center">
										<a href="javascript:void(0)" class="widget active widget-hover-effect1 nsBoton" data-next="form-solicitudes" data-val="Cuentas y Accesos" data-type="segundaVista" style="padding-top:20px; border-radius: 20px; background-color: rgba(205, 210, 5, 0.62); color:#394263; min-height:269px;"><i class="fa fa-users fa-5x"></i>
								            <div class="widget-simple text-center">
								                <h3 class="widget-content text-center animation-pullDown" style="height: 40px !important;">
								                 <strong>Cuentas y Accesos</strong><br>
								                </h3>
								                <strong>Crear cuentas, habilitar accesos y permisos a usuarios o solución de problemas relacionados.</strong>
								            </div>
							        	</a>
									</div>			
								</div>
								<!--TerceraVista -->														
								<div class="row strap nsBoton-aplicaciones hidden">
									<div class="col-md-4 text-center ">
										<a href="javascript:void(0)" class="widget active widget-hover-effect1 nsBoton" data-next="form-solicitudes" data-val="Desbloquear/Cambiar Password" data-type="terceraVista" style="padding-top:20px; border-radius: 20px; background-color: rgba(205, 210, 5, 0.62); color:#394263;"><i class="fa fa-unlock fa-5x"></i>
								            <div class="widget-simple text-center">
								                <h3 class="widget-content text-center animation-pullDown" style="height: 40px !important;">
								                 <strong>Desbloquear/Cambiar Password</strong><br>
								                </h3>
								                <strong>Admininistrar contraseñas de aplicaciones.</strong>
								            </div>
							        	</a>
									</div>	
									<div class="col-md-4 text-center">
										<a href="javascript:void(0)" class="widget active widget-hover-effect1 nsBoton" data-next="form-solicitudes" data-val="Instalar/Configurar" data-type="terceraVista" style="padding-top:20px; border-radius: 20px; background-color: rgba(205, 210, 5, 0.62); color:#394263;"><i class="fa fa-key fa-5x"></i>
								            <div class="widget-simple text-center">
								                <h3 class="widget-content text-center animation-pullDown" style="height: 40px !important;">
								                 <strong>Instalar/Configurar</strong><br>
								                </h3>
								                <strong>Administrar aplicaciones.</strong>
								            </div>
							        	</a>
									</div>	
									<div class="col-md-4 text-center">
										<a href="javascript:void(0)" class="widget active widget-hover-effect1 nsBoton" data-next="form-solicitudes" data-val="Solucionar Problema" data-type="terceraVista" style="padding-top:20px; border-radius: 20px; background-color: rgba(205, 210, 5, 0.62); color:#394263;"><i class="fa fa-check-square-o fa-5x"></i>
								            <div class="widget-simple text-center">
								                <h3 class="widget-content text-center animation-pullDown" style="height: 40px !important;">
								                 <strong>Solucionar Problema</strong><br>
								                </h3>
								                <strong>Administrar problemas de aplicaciones.</strong>
								            </div>
							        	</a>
									</div>											
								</div>								

								<!-- Formulario -->			
								<div class="nsBoton-form-solicitudes hidden strap">
									<fieldset>
										<div class="row">
											<div class="col-md-6">
												<div class="form-group">

											<label class="col-md-4 control-label" for="scsl_cdg">
												<i class="fa fa-user">&nbsp;&nbsp;</i>Destinatario:</label>
											<div class="col-md-8">
												<input type="text" class="form-control" >
											</div>
										</div>
											</div>
											<div class="col-md-6">
												<div class="form-group">
											<label class="col-md-4 control-label" for="scsl_cdg">
												<i class="fa fa-line-chart">&nbsp;&nbsp;</i>Impacto:</label>
											<div class="col-md-8">
												<select name="tipoTurno" class="form-control select-chosen" data-placeholder="Seleccione tipo de turno" style="display: none;">
													<option value="" selected="selected"></option>
													<option value="ALTO">Alto</option>
													<option value="MEDIO">Medio</option>
													<option value="BAJO">Bajo</option>
												</select>
											</div>
										</div>
											</div>
										</div>
									</fieldset>
									<br>         
								
									<fieldset>
										<div class="row">
											<div class="col-md-6">
												<div class="form-group">
											<label class="col-md-4 control-label" for="scsl_cdg"><i class="fa fa-map-marker">&nbsp;&nbsp;</i>Ubicación:</label>
											<div class="col-md-8">
												<input type="text" class="form-control" >
											</div>
										</div>
											</div>
											<div class="col-md-6">
												<div class="form-group">
											<label class="col-md-4 control-label" for="scsl_cdg">
												<i class="fa fa-exclamation-circle">&nbsp;&nbsp;</i>Urgencia:</label>
											<div class="col-md-8">
												<select name="tipoTurno" class="form-control select-chosen" data-placeholder="Seleccione urgencia" style="display: none;">
													<option value="" selected="selected"></option>
													<option value="ALTO">Muy Urgente</option>
													<option value="MEDIO">Urgente</option>
													<option value="BAJO">Poco Urgente</option>
												</select>
											</div>
										</div>
											</div>
										</div>	 
									</fieldset>
									<br>
									<fieldset>
										<div class="row">
											<div class="col-md-6">
												<div class="form-group">
													<label class="col-md-4 control-label" for="scsl_cdg">
														<i class="fa fa-gears">&nbsp;&nbsp;</i>Servicio Afectado:</label>
													<div class="col-md-8">
														<input type="text" class="form-control" >
													</div>
												</div>
											</div>
											<div class="col-md-6">
												<div class="form-group">
												<label class="col-md-4 control-label" for="scsl_cdg">
													<i class="fa fa-user">&nbsp;&nbsp;</i>CI Afectado:</label>
												<div class="col-md-8">
													<input type="text" class="form-control" >
												</div>
												</div>
											</div>
										</div>	 						
									</fieldset>
									<br>
								<h4><div class="block-title alert alert-warning">Información General</div></h4>
									<fieldset>
										<div class="form-group">
											<label class="col-md-4 control-label" for="horaInicio">
												<i class="fa fa-minus">&nbsp;&nbsp;</i>Título:</label>
											<div class="col-md-8">
												<input type="text" class="form-control" >
												<br>
											</div>
										</div>
										<br>
										<div class="form-group">
											<label class="col-md-4 control-label" for="horaFin">
												<i class="fa fa-navicon">&nbsp;&nbsp;</i>Descripción:</label>
											<div class="col-md-8">
												<textarea class="form-control" rows="4" cols="50"></textarea>
											</div>
										</div>
									</fieldset>	
								</div>								
							</div>
 
                           	<div class="modal-footer">
                                <button type="button" class="btn btn-sm btn-warning" data-dismiss="modal">Cerrar</button>
                                <button id="btnGuardar" type="button" class="btn btn-sm btn-primary hidden nsBoton-form-solicitudes">Guardar</button>
                       	 	</div>                        
                       	 </div>
                    </div>
                </div>

                <!-- END Large Modal -->
				
<style>
#stp-trat-3.form-horizontal .form-group {
    margin-left: 0px;
    margin-right: 0px;
}
.widget-simple .widget-pregunta{
	margin: 1px 0px;
    font-size: 18px;											
}
.style-alt .widget, .style-alt .task-list li{
	background-color: #5bc0de;
}
.h:hover{
	background-color: #46b8da;
}

</style>
	<div id="modal-encuesta" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
            <!-- Updates Title -->
            <div class="block-title" style=" margin: 0px;">
                <button type="button" class="close closeModal" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2><strong>Encuesta</strong></h2>
            </div>
            <!-- END Updates Title -->
            <div class="modal-body">

				<div class="progress progress-striped active">
					<div id="barra-progreso" class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 10%;"></div>
				</div>	
            	<!-- Pregunta 1 -->

				<div class="stp-trat"  id="stp-trat-pregunta1">
			
					<h3 class="text-center" style="padding-bottom:50px;">
						¿Cómo considera su desempeño?
					</h3>
					<div class="form-group row text-center">
						<div class="col-lg-12">
							<a href="#" class="widget btn-info stp-trat-btn h" data-next="pregunta2" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
								<div class="widget-simple">
									<img src="<?php echo $this->url->get("/img/icon_feliz.png"); ?>"alt="" height="32px" width="32px">
								</div>
							</a>
						</div>	
						<div class="col-lg-12">
							<a href="#" class="widget btn-info stp-trat-btn" data-next="pregunta2" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
								<div class="widget-simple">
									<img src="<?php echo $this->url->get("/img/icon_normal1.png"); ?>"alt="" height="32px" width="32px">
								</div>
							</a>
						</div>	
						<div class="col-lg-12">
							<a href="#" class="widget btn-info stp-trat-btn" data-next="pregunta2" data-stp="" data-val="" data-type="pregunta1" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
								<div class="widget-simple">
									<img src="<?php echo $this->url->get("/img/icon_triste.png"); ?>"alt="" height="32px" width="32px">
								</div>
							</a>
						</div>													
                    </div>
					<div class="form-group row text-center" style="margin-top: 25px;width: auto;margin-left: -20px;margin-right: -29px;">	
						<div class="btn-group" style="width: 100%;">
							<a href="#" class="btn btn-primary active" style="width: 33%;border-radius: 0px;">Pregunta 1</a>
							<a href="#" class="btn btn-primary" style="width: 33%;" disabled>Pregunta 2</a>
							<a href="#" class="btn btn-primary" style="width: 33%;border-radius: 0px;" disabled>Pregunta 3</a>
						</div>
                    </div>                    
				</div>

				<!-- Pregunta 2 -->

				<div class="stp-trat"  id="stp-trat-pregunta2" style="display:none;">
					<h3 class="text-center" style="padding-bottom:50px;">
						¿Cómo considera el desempeño de sus compañeros?	
					</h3>				
					<div class="form-group row text-center">
							<div class="col-lg-12">
								<a href="#" class="widget btn-info stp-trat-btn" data-next="pregunta3" data-stp="" data-val="" data-type="pregunta2" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
									<div class="widget-simple">
										<img src="<?php echo $this->url->get("/img/icon_feliz.png"); ?>"alt="" height="32px" width="32px">
									</div>
								</a>
							</div>														
							<div class="col-lg-12">
								<a href="#" class="widget btn-info stp-trat-btn" data-next="pregunta3" data-stp="" data-val="" data-type="pregunta2" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
									<div class="widget-simple">
										<img src="<?php echo $this->url->get("/img/icon_normal1.png"); ?>"alt="" height="32px" width="32px">
									</div>
								</a>
							</div>	
							<div class="col-lg-12">
								<a href="#" class="widget btn-info stp-trat-btn" data-next="pregunta3" data-stp="" data-val="" data-type="pregunta2" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
									<div class="widget-simple">
										<img src="<?php echo $this->url->get("/img/icon_triste.png"); ?>"alt="" height="32px" width="32px">
									</div>
								</a>
							</div>														
					</div>
					<div class="form-group row text-center" style="margin-top: 25px;width: auto;margin-left: -20px;margin-right: -29px;">	
						<div class="btn-group" style="width: 100%;">
							<a href="#" class="btn btn-primary stp-trat-btn-menu" data-next="pregunta1" style="width: 33%;border-radius: 0px;">Pregunta 1</a>
							<a href="#" class="btn btn-primary active" style="width: 33%;">Pregunta 2</a>
							<a href="#" class="btn btn-primary" style="width: 33%;border-radius: 0px;" disabled>Pregunta 3</a>
						</div>
					</div>															
				</div>	

				<!-- Pregunta 3 -->

				<div class="stp-trat"  id="stp-trat-pregunta3" style="display:none;">
					<h3 class="text-center" style="padding-bottom:50px;">
						¿Cómo considera el desempeño de sus superiores?
					</h3>				
					<div class="form-group row text-center">
						<div class="col-lg-12">
							<a href="#" class="widget btn-info stp-trat-btn" data-next="resultado" data-stp="pregunta3" data-val="OD" data-type="pregunta3" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
								<div class="widget-simple">
									<img src="<?php echo $this->url->get("/img/icon_feliz.png"); ?>"alt="" height="32px" width="32px">
								</div>
							</a>
						</div>												
						<div class="col-lg-12">
							<a href="#" class="widget btn-info stp-trat-btn" data-next="resultado" data-stp="pregunta3" data-val="" data-type="pregunta3" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
								<div class="widget-simple">
									<img src="<?php echo $this->url->get("/img/icon_normal1.png"); ?>"alt="" height="32px" width="32px">
								</div>
							</a>
						</div>												
					</div>	
					<div class="form-group row text-center">
						<div class="col-lg-12">
							<a href="#" class="widget btn-info stp-trat-btn" data-next="resultado" data-stp="pregunta3" data-val="" data-type="pregunta3" style="-webkit-transform:translateY(-3px);transform:translateY(-3px);-webkit-box-shadow:0 5px 5px rgba(0,0,0,.1);box-shadow:0 5px 5px rgba(0,0,0,.1)">
								<div class="widget-simple">
									<img src="<?php echo $this->url->get("/img/icon_triste.png"); ?>"alt="" height="32px" width="32px">
								</div>
							</a>
						</div>												
					</div>
					<div class="form-group row text-center" style="margin-top: 25px;width: auto;margin-left: -20px;margin-right: -29px;">	
						<div class="btn-group" style="width: 100%;">
							<a href="#" class="btn btn-primary stp-trat-btn-menu" data-next="pregunta1" style="width: 33%;border-radius: 0px;">Pregunta 1</a>
							<a href="#" class="btn btn-primary stp-trat-btn-menu" style="width: 33%;" data-next="pregunta2">Pregunta 2</a>
							<a href="#" class="btn btn-primary active" style="width: 33%;border-radius: 0px;">Pregunta 3</a>
						</div>
					</div>																		
				</div>	

				<!-- Resultado -->		

				<div class="stp-trat"  id="stp-trat-resultado" style="display:none;">
					<div class="form-group row text-center" style="margin-top: -15px;">
						<div class="col-lg-12"  style="margin-top:20%">
							<h2><i class="fa fa-hand-peace-o"></i>¡<strong>Gracias</strong> por responder!</h2> <br>
						</div>
					</div>
				</div>																							
            </div>



		
            <div class="modal-footer">
                <div class="btn-group btn-group-sm pull-right">
                    <a class="btn btn-sm btn-default pull-right" data-dismiss="modal" href=""> Cerrar</a>
                </div>
            </div>
		</div>
	</div>
	</div>
                </div>
                <!-- END Main Container -->
            </div>
            <!-- END Page Container -->
        </div>
		<!-- END Page Wrapper -->

		<a href="#" id="to-top"><i class="fa fa-angle-double-up"></i></a>

		<!-- Remember to include excanvas for IE8 chart support -->
		<!--[if IE 8]><?php print($this->tag->javascriptInclude("js/helpers/excanvas.min.js"))?><![endif]-->

		<!-- jQuery, Bootstrap.js, jQuery plugins and Custom JS code -->
		<?php print($this->tag->javascriptInclude("js/vendor/jquery-1.11.3.min.js"))?>
		<?php print($this->tag->javascriptInclude("js/vendor/bootstrap.min.js"))?>
		<?php print($this->tag->javascriptInclude("js/plugins.js"))?>
		<?php print($this->tag->javascriptInclude("js/app.js"))?>
		<?php print($this->tag->javascriptInclude("js/mifaces.js"))?>
		
		<!--<script src="<?php //print($this->config->item('socketServer'))?>/socket.io/socket.io.js"></script>-->
		<script>
			/*var nodeServer = '<?php //print($this->config->item('socketServer'))?>';
			var socket = io(nodeServer);*/
		</script>		

	    <script>
			$('.nsBoton').click(function(event) {
				$('.strap').addClass('hidden');

				if($(this).data('next') == 'inicial'){
					$('#bcInicio').addClass('hidden');
					$('#textInicio').removeClass('hidden');	
					$('.nsMenu').addClass('hidden');
					$('.nsBoton-inicial').removeClass('hidden');
					$('#infoTitle').html('Seleccione tipo de solicitud');
					$('#btnGuardar').addClass('hidden');
				}
				if($(this).data('next') == 'tecnologia'){
					$('#textInicio').addClass('hidden');
					$('#bcInicio').removeClass('hidden');
					$('.nsBoton-tecnologia').removeClass('hidden');
				}
				if($(this).data('next') == 'aplicaciones'){
					$('.nsBoton-aplicaciones').removeClass('hidden');	
				}

				if($(this).data('next') == 'form-solicitudes'){
					$('#textFormSolicitudes').removeClass('hidden');
					if($(this).data('type') == 'terceraVista'){
						$('#textFormSolicitudes').html($(this).data('val'));				
					} else if ($(this).data('type') == 'segundaVista') {
						$('#textFormSolicitudes').html($(this).data('val'));						
					} else if ($(this).data('type') == 'primeraVista') {
						$('#bcInicio').removeClass('hidden');
						$('#textInicio').addClass('hidden');
						$('#textFormSolicitudes').html($(this).data('val'));
					}
					$('#infoTitle').html('Información Específica');
					$('.nsBoton-form-solicitudes').removeClass('hidden');	
				}
	        });                    	
	    </script>			

		<script>


            // Get the elements where we will attach the charts
            var dashWidgetChart = $('#dash-widget-chart');

            // Random data for the chart
            var dataEarnings = [[1, 1560], [2, 1650], [3, 1320], [4, 1950], [5, 1800]];
            var dataSales = [[1, 800], [2, 847], [3, 480], [4, 950], [5, 600]];
            var dataPendientes = [[1, 583], [2, 782], [3, 749], [4, 273], [5, 356]];
            var dataCurso = [[1, 291], [2, 385], [3, 185], [4, 592], [5, 527]];

            // Array with month labels used in chart
            var chartMonths = [[1, 'Enero'], [2, 'Febrero'], [3, 'Marzo'], [4, 'Abril'], [5, 'Mayo']];

            // Initialize Dash Widget Chart
            $.plot(dashWidgetChart,
                [
                    {
                        data: dataEarnings,
                        lines: {show: true, fill: false},
                        points: {show: true, radius: 6, fillColor: 'green'}
                    },
                    {
                        data: dataSales,
                        lines: {show: true, fill: false},
                        points: {show: true, radius: 6, fillColor: '#CACA08'}
                    },
                    {
                        data: dataPendientes,
                        lines: {show: true, fill: false},
                        points: {show: true, radius: 6, fillColor: '#C30101'}
                    },
                    {
                        data: dataCurso,
                        lines: {show: true, fill: false},
                        points: {show: true, radius: 6, fillColor: 'grey'}
                    }                   
                ],
                {
                    colors: ['#ffffff', 'white','white','white'],
                    legend: {show: false},
                    grid: {borderWidth: 0, hoverable: true, clickable: true},
                    yaxis: {show: false},
                    xaxis: {show: false, ticks: chartMonths}
                }
            );          

            // Creating and attaching a tooltip to the widget
            var previousPoint = null, ttlabel = null;
            dashWidgetChart.bind('plothover', function(event, pos, item) {

                if (item) {
                    if (previousPoint !== item.dataIndex) {
                        previousPoint = item.dataIndex;

                        $('#chart-tooltip').remove();
                        var x = item.datapoint[0], y = item.datapoint[1];

                        // Get xaxis label
                        var monthLabel = item.series.xaxis.options.ticks[item.dataIndex][1];

                        if (item.seriesIndex === 1) {
                            ttlabel = '<strong>' + y + '</strong> Cerradas en <strong>' + monthLabel + '</strong>';
                        } else if(item.seriesIndex === 2) {
                            ttlabel = '<strong>' + y + '</strong> Pendientes en <strong>' + monthLabel + '</strong>';
                        } else if(item.seriesIndex === 3) {
                            ttlabel = '<strong>' + y + '</strong> En Curso en <strong>' + monthLabel + '</strong>';
                        } else {
                            ttlabel = '<strong>' + y + '</strong> Abiertas en <strong>' + monthLabel + '</strong>';
                        }


                        $('<div id=chart-tooltip class=chart-tooltip >' + ttlabel + '</div>')
                            .css({top: item.pageY - 50, left: item.pageX - 50}).appendTo('body').show();
                    }
                }
                else {
                    $('#chart-tooltip').remove();
                    previousPoint = null;
                }
            });

            $.plot('#placeholder', data, {
					    series: {
					        pie: { 
					            show: true,
					            radius: 1,
					            label: {
					                show: true,
					                radius: 3/4,
					                formatter: labelFormatter,
					                background: { 
					                    opacity: 0.5,
					                    color: '#000'
					                }
					            }
					        }
					    },
					    legend: {
					        show: false
					    }
					}); 			
		</script>		

			
		<?php
		if(isset($jsScript) && $jsScript!=null){
		?>
		<script>
		<?php print($jsScript)?>
		</script>
		<?php
			}
		?>		
		<?php
			if(isset($addJs) && $addJs!=null){
				foreach($addJs as $link){
		?>
		<?php print($this->tag->javascriptInclude($link))?>
		<?php
				}
			}
		?>
		<?php
		if(isset($jsPosScrt) && $jsPosScrt!=null){
		?>
		<script>
		<?php print($jsPosScrt)?>
		</script>
		<?php
			}
		?>		
	</body>
</html>