<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
<head>
	<meta charset="utf-8">

	<title><?php print($this->config->appTitle)?></title>

	<meta name="description" content="<?php print($this->config->appTitle)?>">
	<meta name="author" content="<?php print($this->config->appAutor)?>">
	<meta name="robots" content="noindex, nofollow">

	<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

	<!-- Icons -->
	<!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
	<link rel="shortcut icon" href="assets/img/favicon.png">
	<link rel="apple-touch-icon" href="assets/img/icon57.png" sizes="57x57">
	<link rel="apple-touch-icon" href="assets/img/icon72.png" sizes="72x72">
	<link rel="apple-touch-icon" href="assets/img/icon76.png" sizes="76x76">
	<link rel="apple-touch-icon" href="assets/img/icon114.png" sizes="114x114">
	<link rel="apple-touch-icon" href="assets/img/icon120.png" sizes="120x120">
	<link rel="apple-touch-icon" href="assets/img/icon144.png" sizes="144x144">
	<link rel="apple-touch-icon" href="assets/img/icon152.png" sizes="152x152">
	<link rel="apple-touch-icon" href="assets/img/icon180.png" sizes="180x180">
	<!-- END Icons -->

	<!-- Stylesheets -->
	<!-- Bootstrap is included in its original form, unaltered -->
    <?php print($this->tag->stylesheetLink("css/bootstrap.min.css"))?>

	<!-- Related styles of various icon packs and plugins -->
    <?php print($this->tag->stylesheetLink("css/plugins.css"))?>

	<!-- The main stylesheet of this template. All Bootstrap overwrites are defined in here -->
    <?php print($this->tag->stylesheetLink("css/main.css"))?>

	<!-- The themes stylesheet of this template (for using specific theme color in individual elements - must included last) -->
    <?php print($this->tag->stylesheetLink("css/themes.css"))?>

    <!-- tema personalizado para bc -->
    <?php print($this->tag->stylesheetLink("css/bcentral-custom.css"))?>
	<!-- END Stylesheets -->

	<?php
		if(isset($addCss)){
			foreach($addCss as $link){
				print($this->tag->stylesheetLink($link));
			}
		}
	?>
	
	<!-- Modernizr (browser feature detection library) & Respond.js (enables responsive CSS code on browsers that don't support it, eg IE8) -->
	<?php print($this->tag->javascriptInclude("js/vendor/modernizr-respond.min.js"))?>

</head>
<body class="page-loading">
		<div id="page-container" class="style-alt">
	        <!-- Main Container -->
	        <div id="main-container">

	            <header class="navbar navbar-default theme-banco-central ">
	                <!-- Navbar Header -->
		            <div class="navbar-header">
		                <!-- Horizontal Menu Toggle + Alternative Sidebar Toggle Button, Visible only in small screens (< 768px) -->
		                <ul class="nav navbar-nav-custom pull-right visible-xs">
		                    <li>
		                        <a href="javascript:void(0)" data-toggle="collapse" data-target="#horizontal-menu-collapse">Menu</a>
		                    </li>
		                </ul>
		                <!-- END Horizontal Menu Toggle + Alternative Sidebar Toggle Button -->

		            </div>
		            <!-- END Navbar Header -->

		            <div id="horizontal-menu-collapse" class="collapse navbar-collapse">

			            <!-- Alternative Sidebar Toggle Button, Visible only in large screens (> 767px) -->
			            <ul class="nav navbar-nav-custom pull-right hidden-xs">
							<li class="dropdown">
			                    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
			                        <i class="gi gi-user"></i><strong> Alejandro Aguilera</strong> <i class="fa fa-angle-down"></i>
			                    </a>
			                    <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
			                        <li class="dropdown-header text-center">Opciones</li>
			                        <li>
			                            <a href="page_ready_timeline.php">
			                                <i class="fa fa-ban fa-fw pull-right"></i>
			                                Desconectarse
			                            </a>
			                        </li>

			                    </ul>
			                </li>
			            </ul>
		            </div>
	            </header>
	            <!-- END Header -->

	            <!-- Page Content -->
	            <div id="page-content" class="clearfix">
	                <!-- Dashboard Header -->
				    <!-- For an image header add the class 'content-header-media' and an image as in the following example -->
				    <div class="content-header content-header-media">
				        <div class="header-section header-section-bc">
				            <div class="row">
				                <!-- Main Title (hidden on small devices for the statistics to fit) -->
				                <div class="col-md-2 col-lg-1 col-xs-2">
				               		<img src="<?php print($this->url->get("img/bc-chile-icon.png"))?>" style="width: 100%;opacity: 0.8;">
				                </div>
				                <div class="col-md-6 col-lg-6 col-xs-6">
				                    <h1>Bienvenido al <strong>Portal TI</strong><br><small>Banco Central de Chile</small></h1>
				                </div>
				                <!-- END Main Title -->

				                <!-- Top Stats -->

				                <!-- END Top Stats -->
				            </div>
				        </div>
				        <!-- For best results use an image with a resolution of 2560x248 pixels (You can also use a blurred image with ratio 10:1 - eg: 1000x100 pixels - it will adjust and look great!) -->
				        <img src="<?php print($this->url->get("img/background-encabezado2.png"))?>" alt="header image" class="" style="width: 100%;opacity: 0.9;">
				    </div>
				    <!-- END Dashboard Header -->

				    <!-- Widgets Row -->
				    <div class="row">
				    	<div class="col-lg-12">
	                    	<div id="breadcrumbs">
								<span class="  ">
									<i class="fa fa-arrow-right"></i>	
									<span id="textTecnologia"><a href="<?php print($this->url->get('comercio')) ?>">Inicio</a></span>
								</span>
								<span class="  ">
									<i class="fa fa-arrow-right"></i>	
									<span id="textAplicaciones"  >Base de Conocimiento</span>
								</span>
	                    	</div>
	                    	<br><br>
						<div class="widget ">
						   <div class="widget-extra themed-background-dark">
						  		 <h3 class="widget-content-light">
			          	             Busqueda en <strong>Base Conocimiento</strong>
			                        <small><a href=""><strong></strong></a></small>
			                    </h3>
						   </div>
			                    <div class="col-lg-12" style="padding: 70px 150px 10px 150px;">
					                 <div class="form-group">
					                    <div class="col-md-12">
					                        <div class="input-group">
					                            <input type="email" id="example-input2-group2"  value="contraseña" name="example-input2-group2" class="form-control" placeholder="palabras claves a buscar">
					                            <span class="input-group-btn">
					                                <button type="button" class="btn btn-primary"> <i class="fa fa-search"></i> Buscar</button>
					                            </span>
					                        </div>
					                    </div>
					                </div>
				                </div>
		        				<table class="table table-striped table-vcenter">
				                    <thead>
				                        <tr>
				                            <th><i class="fa fa-briefcase"></i> Titulo Resultado</th>
				                            <th class="text-center hidden-xs" style="width: 20%;">Tiene Documento</th>
				                            <th class="text-center hidden-xs" style="width: 20%;"></th>
				                            <th class="text-center" style="min-width: 120px; width: 20%;">Acción</th>
				                        </tr>
				                    </thead>
				                    <tbody>
				                        <tr>
				                            <td>
				                                <h3><a href="javascript:void(0)"><strong>Busqueda manual de cambio de contraseña</strong></a></h3>

				                                <p><em>Actualmente los usuarios buscan en menos clic como cambiar la contraseña de su cuenta SSO. </em></p>
				                            </td>
				                            <td class="text-center hidden-xs">
				                                <h3 class="animation-pullDown">SI</h3>
				                            </td>
				                            <td class="text-center hidden-xs">
				                                <h3 class="animation-pullDown"></h3>
				                            </td>
				                            <td class="text-center">
				                                <a href=""><strong>Leer resultado completo </strong></a>
				                            </td>
				                        </tr>
				                        <tr>
				                            <td>
				                                <h3><a href="javascript:void(0)"><strong>Busqueda automatica de cambio de contraseña</strong></a></h3>

				                                <p><em>En los ultimos 3 dias los usuarios cambiaron su contraseña automaticamente. </em></p>
				                            </td>
				                            <td class="text-center hidden-xs">
				                                <h3 class="animation-pullDown">NO</h3>
				                            </td>
				                            <td class="text-center hidden-xs">
				                                <h3 class="animation-pullDown"></h3>
				                            </td>
				                            <td class="text-center">
				                                <a href=""><strong>Leer resultado completo </strong></a>
				                            </td>
				                        </tr>
				                        
				                    </tbody>
				                </table>

		                    	
						    </div>
					    </div>

				</div>



			</div>
			 				<!-- Footer -->
	            <footer class="clearfix">
	                <div class="pull-right">
	                	<a href="http://www.bccentral.cl" >Banco Central de Chile</a>
	            	</div>
		            <div class="pull-left">
		                <span id="year-copy"></span> 2016 &copy; <a href="" target="_blank">Portal TI - BCCH</a>
		            </div>
	            </footer>
	            <!-- END Footer -->
		</div>



	<!-- Remember to include excanvas for IE8 chart support -->
	<!--[if IE 8]><?php print($this->tag->javascriptInclude("js/helpers/excanvas.min.js"))?><![endif]-->

	<!-- jQuery, Bootstrap.js, jQuery plugins and Custom JS code -->
	<?php print($this->tag->javascriptInclude("js/vendor/jquery-1.11.3.min.js"))?>
	<?php print($this->tag->javascriptInclude("js/vendor/bootstrap.min.js"))?>
	<?php print($this->tag->javascriptInclude("js/plugins.js"))?>

	<script>
		$(document).ready(function() {
		    $("div.bhoechie-tab-menu>div.list-group>a").click(function(e) {
		        e.preventDefault();
		        $(this).siblings('a.active').removeClass("active");
		        $(this).addClass("active");
		        var index = $(this).index();
		        $("div.bhoechie-tab>div.bhoechie-tab-content").removeClass("active");
		        $("div.bhoechie-tab>div.bhoechie-tab-content").eq(index).addClass("active");
		    });
		});
	</script>
	<?php
	if(isset($jsScript) && $jsScript!=null){
	?>
	<script>
	<?php print($jsScript)?>
	</script>
	<?php
		}
	?>		
	<?php
		if(isset($addJs) && $addJs!=null){
			foreach($addJs as $link){
	?>
	<?php print($this->tag->javascriptInclude($link))?>
	<?php
			}
		}
	?>
	<?php
	if(isset($jsPosScrt) && $jsPosScrt!=null){
	?>
	<script>
	<?php print($jsPosScrt)?>
	</script>
	<?php
		}
	?>	
</body>
</html>