    <!-- BREADCRUMBS -->
    <div  class="header-pages">
        <div id="modal_header_1">
            <h3 class="modal-title_1"> Consultar <strong> Solicitudes</strong></h3>
        </div>
        <div id="breadcrumbs">
            <span class="bcTecnologia nsMenu">
                <a href="<?php print($this->url->get("comercio"))?>"><span id="textTecnologia">Inicio</span></a>
            </span>
            <span class="bcTecnologia nsMenu">
                <i class="fa fa-arrow-right"></i>   
                <span id="textTecnologia">Solicitudes</span>
            </span>                            
        </div>

    </div>
    <!-- ./BREADCRUMBS -->


				                        <!-- Tickets List -->
                    <div class="block full">
                        <div class="block-content-full">
                            <div class="table-responsive remove-margin-bottom">
                            <form id="evaluacionForm" action="<?php print $this->url->get('comercio/evaluarAtencionModal') ?>" method="post" enctype="multipart/form-data" data-type="ajax">
                                <table id="table" class="table table-striped table-vcenter  table-condensed remove-margin-bottom">
                                    <thead>
                                        <tr>
                                            <th class="text-center">Nº Ticket</th>
                                            <th>Estado</th>
                                            <th>Descripción Breve</th>
                                            <th class="text-center">Evaluar Ticket    </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td class="text-center bc-text"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK420</a></td>
                                            <td><span class="label label-danger">PENDIENTE</span></td>
                                            <td>
                                                <strong class="bc-text">Necesito cambiar contraseña usuario SSO</strong><br>
                                                <span class="text-muted">7/03/2016 <strong> 16:40 </strong></span>
                                            </td>
                                            <td class="text-center bc-text"> </td>
                                        </tr>
                                        <tr>
                                            <td class="text-center bc-text"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK421</a></td>
                                            <td><span class="label label-success">EN CURSO</span></td>
                                            <td>
                                                <strong class="bc-text">Necesito cambiar contraseña usuario SSO</strong><br>
                                                <span class="text-muted">7/03/2016 <strong> 16:40 </strong></span>
                                            </td>
                                            <td class="text-center bc-text"> </td>
                                        </tr>
                                        <tr>
                                            <td class="text-center bc-text"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK422</a></td>
                                            <td><span class="label label-default">CERRADO</span></td>
                                            <td>
                                                <strong class="bc-text">Necesito cambiar contraseña usuario SSO</strong><br>
                                                <span class="text-muted">7/03/2016 <strong> 16:40 </strong></span>
                                            </td>
                                            <td class="text-center bc-text">
                                                <div class="like-selector">
                                                    <input  id="like11" type="radio" name="conf1" value="1" />
                                                    <label class="option-like like" for="like11"></label>
                                                    <input id="like12" type="radio" name="conf1" value="2" />
                                                    <label class="option-like dislike"for="like12"></label>
                                                </div>
                                            </td>
                                        </tr>
                                         <tr>
                                            <td class="text-center bc-text"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK423</a></td>
                                            <td><span class="label label-success">EN CURSO</span></td>
                                            <td>
                                                <strong class="bc-text">Necesito cambiar contraseña usuario SSO</strong><br>
                                                <span class="text-muted">7/03/2016 <strong> 16:40 </strong></span>
                                            </td>
                                            <td class="text-center bc-text"></td>
                                        </tr>
                                        <tr>
                                            <td class="text-center bc-text"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK424</a></td>
                                            <td><span class="label label-success">EN CURSO</span></td>
                                            <td>
                                                <strong class="bc-text">Necesito cambiar contraseña usuario SSO</strong><br>
                                                <span class="text-muted">7/03/2016 <strong> 16:40 </strong></span>
                                            </td>
                                            <td class="text-center bc-text"></td>
                                        </tr>
                                        <tr>
                                            <td class="text-center bc-text"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK425</a></td>
                                            <td><span class="label label-default">CERRADO</span></td>
                                            <td>
                                                <strong class="bc-text">Necesito cambiar contraseña usuario SSO</strong><br>
                                                <span class="text-muted">7/03/2016 <strong> 16:40 </strong></span>
                                            </td>
                                            <td class="text-center bc-text"> 
                                                <div class="like-selector">
                                                    <input  id="like21" type="radio" name="conf2" value="1" />
                                                    <label class="option-like like" for="like21"></label>
                                                    <input id="like22" type="radio" name="conf2" value="2" />
                                                    <label class="option-like dislike"for="like22"></label>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="text-center bc-text"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK426</a></td>
                                            <td><span class="label label-default">CERRADO</span></td>
                                            <td>
                                                <strong class="bc-text">Necesito cambiar contraseña usuario SSO</strong><br>
                                                <span class="text-muted">7/03/2016 <strong> 16:40 </strong></span>
                                            </td>
                                            <td class="text-center bc-text"> 
                                                <div class="like-selector">
                                                    <input  id="like31" type="radio" name="conf3" value="1" />
                                                    <label class="option-like like" for="like31"></label>
                                                    <input id="like32" type="radio" name="conf3" value="2" />
                                                    <label class="option-like dislike"for="like32"></label>
                                                </div>
                                            </td>
                                        </tr>
                                         <tr>
                                            <td class="text-center bc-text"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK424</a></td>
                                            <td><span class="label label-success">EN CURSO</span></td>
                                            <td>
                                                <strong class="bc-text">Necesito cambiar contraseña usuario SSO</strong><br>
                                                <span class="text-muted">7/03/2016 <strong> 16:40 </strong></span>
                                            </td>
                                            <td class="text-center bc-text"></td>
                                        </tr>
                                        <tr>
                                            <td class="text-center bc-text"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK424</a></td>
                                            <td><span class="label label-success">EN CURSO</span></td>
                                            <td>
                                                <strong class="bc-text">Necesito cambiar contraseña usuario SSO</strong><br>
                                                <span class="text-muted">7/03/2016 <strong> 16:40 </strong></span>
                                            </td>
                                            <td class="text-center bc-text"></td>
                                        </tr>
                                        <tr>
                                            <td class="text-center bc-text"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK424</a></td>
                                            <td><span class="label label-success">EN CURSO</span></td>
                                            <td>
                                                <strong class="bc-text">Necesito cambiar contraseña usuario SSO</strong><br>
                                                <span class="text-muted">7/03/2016 <strong> 16:40 </strong></span>
                                            </td>
                                            <td class="text-center bc-text"></td>
                                        </tr>

                                        
                                    </tbody>
                                </table>

                                <input  class="hidden" id="optionLike" name="optionLike" />
                                <input  class="hidden" id="ticketId" name="ticketId" />
                            </form>
                            </div>
                            <div class="text-center">
                                <ul class="pagination">
                                    <li class="disabled"><a href="javascript:void(0)"><i class="fa fa-chevron-left"></i></a></li>
                                    <li class="active"><a href="javascript:void(0)">1</a></li>
                                    <li><a href="javascript:void(0)">2</a></li>
                                    <li><a href="javascript:void(0)">3</a></li>
                                    <li><a href="javascript:void(0)"><i class="fa fa-chevron-right"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- END Tickets List -->


<div id="contenidomodal">
    
</div>


