<form action="<?php print $this->url->get('comercio/TestCreateInteraction') ?>" method="post">
<div class="nsBoton-form-solicitudes strap">
		<div class="row" style="margin-top: -20px;">
			<div class="col-md-8 center-block" style="text-align: center; padding-bottom: 15px;">
				<h4><div class="alert" style="color:white ;background-color: #002453;border-color: #002453;">Datos <strong>Solicitud</strong></div></h4>
			</div>

			
			<div class="col-md-8 center-block">
			
			<?php if($pcData['campos']['detinatario'] == 'si') {?>
			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<label class="col-md-4 control-label" for="scsl_cdg">
								<i class="fa fa-user">&nbsp;&nbsp;</i>Destinatario:</label>
							<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Destinatario" data-content="Persona a la que se le entregará el servicio.">
								<select  data-placeholder="Selecciona un Opción"  id="select_dest" name="select_dest" class="select-chosen">
									<?php 
										foreach ($pcData['contactos'] as $key => $value) { ?>
											<option value="<?php echo $value; ?>"><?php echo $value; ?></option>
									<?php	
										}
									 ?>
		                        </select>
							</div>
						</div>
					</div>
					</div>
			</fieldset>
			<?php } 
			if($pcData['campos']['ci'] == 'si') {?>
			<br>
			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
						<label class="col-md-4 control-label" for="select_sa">
							<i class="fa fa-user">&nbsp;&nbsp;</i>Servicio Afectado:</label>
						<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Servicio Afectado" data-content="Blah Blah">
							<select data-placeholder="Selecciona un Opción"  id="select_sa" name="select_sa" class="select-chosen">
                                <option value=""></option>
                                <?php foreach ($pcData['listas'] as $key => $value) {?>
                                	<option value="<?php print $key ?>"><?php print $key ?></option>
                                <?php } ?>
	                        </select>
						</div>
						</div>
					</div>
				</div>	 						
			</fieldset>
			<br>
			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
						<label class="col-md-4 control-label" for="scsl_cdg">
							<i class="fa fa-user">&nbsp;&nbsp;</i>Componente:</label>
						<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Componente" data-content="Componente de Tecnología (Sistema, Hardware, Software)">
							<select data-placeholder="Selecciona un Opción"  id="select_ci" name="select_ci" class="select-chosen">
                                <option value=""></option>
	                        </select>
						</div>
						</div>
					</div>
				</div>	 						
			</fieldset>
			<?php } 
			if($pcData['campos']['descripcion'] == 'si') {?>
			<br>

			<fieldset>
				<div class="form-group">
					<label class="col-md-4 control-label" for="horaInicio">
						<i class="fa fa-minus">&nbsp;&nbsp;</i>Descripción Breve:</label>
					<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Descripción Breve" data-content="Blah Blah Blah ..">
						<input type="text" name="title" class="form-control" >
						<br>
					</div>
				</div>
				<br>
				<div class="form-group">
					<label class="col-md-4 control-label" for="horaFin">
						<i class="fa fa-navicon">&nbsp;&nbsp;</i>Otros Antecedentes:</label>
					<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Otros Antecedentes" data-content="Blah Blah Blah ..">
						<textarea class="form-control" rows="4" cols="50" name="description"></textarea>
					</div>
				</div>
			</fieldset>
			<?php }
			 if($pcData['campos']['interrupcion'] == 'si') {?>
			<br>

			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
						<label class="col-md-4 control-label" for="scsl_cdg">
							<i class="fa fa-user">&nbsp;&nbsp;</i>Hay Interrupción de Servicio ?:</label>
						<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Interrupción de Servicio" data-content="Blah Blah Blah ..">
							<select data-placeholder="Selecciona un Opción"  id="select_is" name="select_is" class="select-chosen">
                                    <option value="SI">SI</option>
                                    <option selected="selected" value="NO">NO</option>
	                        </select>
						</div>
						</div>
					</div>
				</div>	 						
			</fieldset>
			<?php }
			if($pcData['campos']['impacto'] == 'si') {?>
			<br>

			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<label class="col-md-4 control-label" for="scsl_cdg">
								<i class="fa fa-line-chart">&nbsp;&nbsp;</i>Impacto:</label>
							<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Impacto" data-content="Blah Blah Blah ..">
								<select data-placeholder="Selecciona un Opción"  id="select_i" name="select_i" class="select-chosen">
	                                <option value="4">Empresa</option>
	                                <option value="3">Sitio/Dpto</option>
	                                <option value="2">Varios Usuarios</option>
	                                <option value="1" selected="selected">Usuario</option>
		                        </select>
							</div>
						</div>
					</div>
				</div>
			</fieldset>
			<?php }
			if($pcData['campos']['urgencia'] == 'si') { ?>
			<br>

			<fieldset>
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
						<label class="col-md-4 control-label" for="scsl_cdg">
						<i class="fa fa-exclamation-circle">&nbsp;&nbsp;</i>Urgencia:</label>
							<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Urgencia" data-content="Blah Blah Blah ..">
								<select data-placeholder="Selecciona un Opción"  id="select_u" name="select_u" class="select-chosen">
	                                <option value="1">Crítica</option>
	                                <option value="2">Alta</option>
	                                <option value="3">Media</option>
	                                <option value="4" selected="selected">Baja</option>
		                        </select>
							</div>
						</div>
					</div>
				</div>	 
			</fieldset>
			<?php }
			 if($pcData['campos']['desde'] == 'si') {?>
			<br>

			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<label class="col-md-4 control-label" for="scsl_cdg"><i class="fa fa-calendar">&nbsp;&nbsp;</i>Desde:</label>
							<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Desde" data-content="Blah Blah Blah ..">
								<input type="text" class="form-control input-datepicker" name="desde" data-date-format="dd-mm-yyyy">
							</div>
						</div>
					</div>
				</div>
			</fieldset>
			<?php }
			if($pcData['campos']['hasta'] == 'si') { ?>
			<br>

			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<label class="col-md-4 control-label" for="scsl_cdg"><i class="fa fa-calendar">&nbsp;&nbsp;</i>Hasta:</label>
							<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Hasta" data-content="Blah Blah Blah ..">
								<input type="text" class="form-control input-datepicker" name="hasta" data-date-format="dd-mm-yyyy">
							</div>
						</div>
					</div>
				</div>
			</fieldset>
			<?php }
			if($pcData['campos']['autorizacion'] == 'si') { ?>
			<br>

			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<label class="col-md-4 control-label" for="scsl_cdg">
							</label>	
							<div class="col-md-8">
							<div class="alert alert-warning alert-dismissable">
			                    <i class="fa fa-exclamation-circle"></i> Se requiere adjunte la autorización de su gerencia para procesar la solicitud de servicio
			                </div>
								
							</div>
						</div>
					</div>
					</div>
			</fieldset>
			<?php } 
			if($pcData['campos']['adjunto'] == 'op') { ?>
			<br>

			<fieldset>
				<div class="form-group">
	                <label class="col-md-4 control-label" for="example-file-multiple-input">Información Adicional</label>
	                <div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Información Adicional" data-content="Blah Blah Blah ..">
	                    <input type="file" id="example-file-multiple-input" name="example-file-multiple-input" multiple="">
	                </div>
	            </div>
			</fieldset>

			<?php } ?>
			<fieldset style="margin-top: 30px;">
				<div class="form-group">
					<input type="hidden" name="area" value="<?php echo $pcData['catalogo']['area']; ?>">
					<input type="hidden" name="subarea" value="<?php echo $pcData['catalogo']['subarea']; ?>">
					<div class="col-xs-4 center-block">
						<button id="btnGuardar" type="button" class="btn btn-block btn-bc">Enviar Solicitud</button>
					</div>
			  	</div>
			</fieldset>
			</div>
		</div>
	</div>
</form>
