    <!-- BREADCRUMBS -->
    <div  class="header-pages">
        <div id="modal_header_1">
            <h3 class="modal-title_1"> Ticket <?php echo $pcData['tck']->CallID;?></strong></h3>
        </div>
        <div id="breadcrumbs">
            <span class="bcTecnologia nsMenu">
                <a href="<?php print($this->url->get("comercio"))?>"><span id="textTecnologia">Inicio</span></a>
            </span>
            <span class="bcTecnologia nsMenu">
                <i class="fa fa-arrow-right"></i>   
                <span id="textTecnologia">Tickets</span>
            </span>
            <span class="bcTecnologia nsMenu">
                <i class="fa fa-arrow-right"></i>   
                <span id="textTecnologia"><?php echo $pcData['tck']->CallID;?></span>
            </span>                              
        </div>

    </div>
    <!-- ./BREADCRUMBS -->

    <div class="row">
        <div class="col-sm-4 ">
                <!-- Your Plan Widget -->
                <div class="block">
                    <div class="block-title">
                        <h3>
                           <strong>Datos del ticket </strong>
                            
                        </h3>
                        <div class="block-options pull-right">
                            <a href="<?php print $this->url->get('ajax/loadReiterarTicket') ?>" data-action="<?php print $this->url->get('ajax/loadReiterarTicket') ?>" data-val="tck=<?php print $pcData['tck']->CallID ?>">
                            <span class="label btn-bc"> <i class="gi gi-repeat"></i> Insistir</span>
                            <!--<span class="label btn-bc"> <i class="gi gi-repeat"></i>Evaluar</span>-->
                            </a>
                        </div>

                    </div>
                                                            <?php  
                                                            $label = "bc";
                                                            if ($pcData['tck']->Status == 'Aceptado' or (strpos($pcData['tck']->Status, 'Abierto') !== false)) {
                                                                $label = "encurso";
                                                            }
                                                            else if(strpos($pcData['tck']->Status, 'Pendiente') !== false)
                                                            {
                                                                 $label = "pendiente";
                                                            } else if(strpos($pcData['tck']->Status, 'Rechazado') !== false)
                                                            {
                                                                 $label = "rechazado";
                                                            }
                                                            else if(strpos($pcData['tck']->Status, 'Cerrado') !== false)
                                                            {
                                                                 $label = "cerrado";
                                                            }
                                                            //cerrado, rechazado y bc 
                                                            ?>
                    <div class="widget-extra-full catalogo-lista-home">
                        <div class="row ">
                                                                    <!-- Tickets List -->
                            <div class="tab-pane active" id="tickets-list">
                                <div class="block-content-full " style="padding-left:30px;padding-right:30px;">
                                    
                                    <span><i class="gi gi-user"></i> Por <strong><?php echo $pcData['tck']->ReportedByContact;?></strong></span> <br>
                                    <span><i class="gi gi-calendar"></i> Fecha Solicitud: <strong><?php echo $pcData['tck']->OpenTime;?></strong></span><br>
                                    <span><i class="gi gi-ok_2"></i> Categoría: <strong><?php echo $pcData['tck']->Area;?></strong></span><br>
                                    <span><i class="gi gi-ok_2"></i> Sub-Categoría: <strong><?php echo $pcData['tck']->Subarea;?></strong></span><br>
                                    <span class="label label-<?php echo $label; ?> br-span"><i class="hi hi-send"></i> Estado: <strong><?php echo $pcData['tck']->Status;?></strong></span><br>
                                    <h3><strong><?php echo $pcData['tck']->Title;?></strong></h3><br>
                                    <h5><strong>Descripción: </strong>
                                        <?php echo $pcData['tck']->Description; ?>
                                    </h5>
                                </div>
                            </div>
                            <!-- END Tickets List -->
                        </div>
                    </div>
                 </div>
                <!-- END Your Plan Widget -->
        </div>

        <div class="col-sm-8 ">
            <!-- Your Plan Widget -->
            <div class="block">
                <div class="block-title">
                    <h3>
                       <strong>Detalle ticket </strong><?php echo $pcData['tck']->CallID;?>
                        
                    </h3>

                </div>
                <div class="widget-extra-full catalogo-lista-home">
                    <div class="row ">
                                                                <!-- Tickets List -->
                        <div class="tab-pane active" id="tickets-list">
                            <div class="block-content-full " style="padding-left:30px;padding-right:30px;">
                               <table class="table table-bordered table-striped table-vcenter">
                                    <tbody>
                                        <tr>
                                            <td class="text-center">Servicio Solicitado</td>
                                            <td >Servicios TI - Correo Electronico - Crear, Eliminar Cuenta </td>
                                        </tr>
                                        <tr>
                                            <td class="text-center">Destinatario Servicio</td>
                                            <td > <?php echo $pcData['tck']->ServiceRecipient;?></td>
                                        </tr>
                                        <tr>
                                            <td class="text-center" >C.I. Afectado</td>
                                            <td > <?php echo $pcData['tck']->AffectedCI;?></td>
                                        </tr>
                                        <tr>
                                            <td class="text-center" >¿Hay Interrupción de Servicio?</td>
                                            <td ><?php if($pcData['tck']->FailedEntitlement){ echo "Sí"; } else{ echo "No"; }?></td>
                                        </tr>
                                        <tr>
                                            <td class="text-center" >Impacto</td>
                                            <td > <?php echo $pcData['tck']->Impact;?></td>
                                        </tr>
                                        <tr>
                                            <td class="text-center" >Urgencia</td>
                                            <td > <?php echo $pcData['tck']->Urgency;?></td>
                                        </tr>
                                         <tr>
                                            <td class="text-center" >Servicio Afectado</td>
                                            <td > <?php echo $pcData['tck']->AffectedService;?></td>
                                        </tr>
                                        <tr>
                                            <td class="text-center" >Última Actualización</td>
                                            <td > <?php echo $pcData['tck']->UpdateTime;?></td>
                                        </tr>
                                        <!--<tr>
                                            <td class="text-center" >Desde</td>
                                            <td > 16:05 01-04-2016</td>
                                        </tr>
                                         <tr>
                                            <td class="text-center" >Hasta</td>
                                            <td > 16:05 01-04-2017</td>
                                        </tr>-->

                                       
                                    </tbody>
                                </table>

                            </div>
                        </div>
                        <!-- END Tickets List -->
                    </div>
                </div>
             </div>
            <!-- END Your Plan Widget -->



            <!-- Your Plan Widget -->

            <!-- END Your Plan Widget -->
        </div>

        <div class="col-sm-4">
        </div>
        <div class="col-sm-8">
                <div class="block ">
                    <div class="block-title">
                        <h3>
                           <strong>Bitácora </strong>#TICK123
                            
                        </h3>

                    </div>
                    <div class="widget-extra-full catalogo-lista-home">
                        <div class="row ">
                                                                    <!-- Tickets List -->
                            <div class="tab-pane active" id="tickets-list">
                                <div class="block-content-full " style="padding-left:30px;padding-right:30px;">
                                   <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th width="20%">Fecha</th>
                                                <th>Detalle</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td class="text-center">-</td>
                                                <td>-</td>
                                            </tr>
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                            <!-- END Tickets List -->
                        </div>
                    </div>
                 </div>
        </div>

        <div id="modal-reiterar" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        </div>
</div>


<!-- La que vale -->





<div id="modal-reiterar" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog " style="width: 70%">
        <div class="modal-content">
            <!-- Updates Title -->
            <div class="block-title" style=" margin: 0px;">
                <button type="button" class="close closeModal" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2><strong>Insistir Ticket <a href="<?php print($this->url->get('ticket')) ?>" >#TCK442</a></strong></h2>
            </div>
            <!-- END Updates Title -->
            <div class="modal-body">
                <!-- Resultado -->      
                <div class="stp-trat"  id="stp-trat-resultado">
                    <div class="form-group row text-center " style="margin-top: -15px;">
                        <div class="col-lg-12">
                            <h3><strong>Ingresar detalle de la Insistencia</strong></h3> <br>
                        </div>
                        <div class="col-lg-6 center-block">
                           <textarea id="descripcion" name="descripcion" rows="5" class="form-control push-bit" placeholder="descripción"></textarea>
                        </div>
                        <div class="col-lg-6 center-block">
                           <button style="width:100%" type="button" class="btn btn-bc">Enviar Insistencia</button>
                        </div>                                               
                    </div>
                </div>                                                                                          
            </div>

        
            <div class="modal-footer">
                <div class="btn-group btn-group-sm pull-right">
                    <a class="btn btn-sm btn-default pull-right" data-dismiss="modal" href=""> Cerrar</a>
                </div>
            </div>
        </div>
    </div>
</div>