<div id="modal_header_1">
    <h3 class="modal-title_1"> Nueva Solicitud<strong> <?php print $pcData['breadCrumbList'][0][0] ?></strong></h3>
</div>
<div id="breadcrumbs">
		<span class="bcTecnologia nsMenu">
		<a class="bc-text" href="<?php print($this->url->get(""))?>"><span id="textTecnologia">Inicio</span></a>
	</span>
	<?php foreach ($pcData['breadCrumbList'] as $item) {	?>
		<span class="bcTecnologia nsMenu">
			<i class="fa fa-arrow-right"></i>
			<?php if($item[1] == 'active'){ ?>	
				<a class="bc-text" href="<?php print($this->url->get('comercio/solicitudServicio/'.$item[2]))?>"><span id="textTecnologia"><?php print $item[0] ?></span></a>
			<?php } else {?>
				<?php print $item[0] ?>
			<?php } ?>
			
		</span>	
	<?php } ?>					
</div>