    <!-- BREADCRUMBS -->
    <div  class="header-pages">
        <div id="modal_header_1">
            <h3 class="modal-title_1"> Buscar <strong> Preguntas Frecuentes, Procedimientos, Formularios e Instructivos.</strong></h3>
        </div>
        <div id="breadcrumbs">
            <span class="bcTecnologia nsMenu">
                <a href="<?php print($this->url->get("comercio"))?>"><span id="textTecnologia">Inicio</span></a>
            </span>
            <span class="bcTecnologia nsMenu">
                <i class="fa fa-arrow-right"></i>   
                <span id="textTecnologia">Preguntas Frecuentes, Procedimientos, Formularios e Instructivos.</span>
            </span>                            
        </div>

    </div>
    <!-- ./BREADCRUMBS -->


		<div class="widget ">
		   <div class="widget-extra themed-background-dark">
		  		 <h3 class="widget-content-light">
      	             Búsqueda por Palabras
                    <small><a href=""><strong></strong></a></small>
                </h3>
		   </div>
            <div class="col-lg-12" style="padding: 70px 150px 10px 150px;">
                 <div class="form-group">
                    <div class="col-md-12">
                        <div class="input-group">
                            <input type="email" id="example-input2-group2"  value="contraseña" name="example-input2-group2" class="form-control" placeholder="palabras claves a buscar">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-bc"> <i class="fa fa-search"></i> Buscar</button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
				<table class="table table-striped table-vcenter">
                    <thead>
                        <tr>
                            <th><i class="fa fa-briefcase"></i> Resultado Búsqueda</th>
                            <th class="text-center hidden-xs" style="width: 20%;">Tiene Adjunto</th>
                            <th class="text-center hidden-xs" style="width: 20%;"></th>
                            <th class="text-center" style="min-width: 120px; width: 20%;">Acción</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <h5><a href="javascript:void(0)"><strong>Busqueda manual de cambio de contraseña</strong></a></h5>

                                <p><em>Actualmente los usuarios buscan en menos clic como cambiar la contraseña de su cuenta SSO. </em></p>
                            </td>
                            <td class="text-center hidden-xs">
                                <h3 class="animation-pullDown">SI</h3>
                            </td>
                            <td class="text-center hidden-xs">
                                <h3 class="animation-pullDown"></h3>
                            </td>
                            <td class="text-center">
                                <a class="btn btn-bc" href="<?php print($this->url->get('documento')) ?>"><strong>Leer resultado completo </strong></a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h5><a href="javascript:void(0)"><strong>Busqueda automatica de cambio de contraseña</strong></a></h5>

                                <p><em>En los ultimos 3 dias los usuarios cambiaron su contraseña automaticamente. </em></p>
                            </td>
                            <td class="text-center hidden-xs">
                                <h3 class="animation-pullDown">NO</h3>
                            </td>
                            <td class="text-center hidden-xs">
                                <h3 class="animation-pullDown"></h3>
                            </td>
                            <td class="text-center">
                                <a class="btn btn-bc" href="<?php print($this->url->get('documento')) ?>"><strong>Leer resultado completo </strong></a>
                            </td>
                        </tr>
                        
                    </tbody>
                </table>

            	
	    </div>

