

<div class="row">
<div class="col-md-12 center-block">
<!-- Your Plan Widget -->
<div class="">
	<!-- BREADCRUMBS -->
    <div  class="header-pages">
    	<div id="modal_header_1">
            <h3 class="modal-title_1"> Nueva Solicitud<strong> Soporte</strong></h3>
    	</div>
    	<div id="breadcrumbs">
  			<span class="bcTecnologia nsMenu">
				<a href="<?php print($this->url->get("comercio"))?>"><span id="textTecnologia">Inicio</span></a>
			</span>
			<span class="bcTecnologia nsMenu">
				<i class="fa fa-arrow-right"></i>	
				<span id="textTecnologia">Nueva Solicitud Soporte</span>
			</span>							
    	</div>

    </div>
    <!-- ./BREADCRUMBS -->

	<div class="widget-extra-full" style="padding-top: 10px;">
	    <div class="row ">
		    <div class="col-md-8  center-block">
			        <div class="block " style=" min-height: 400px;">
			            <div class="">
					        <div class="form-group">
					            <label class="col-md-3 control-label" for="example-text-input"> <i class="fa fa-user"></i> Solicitante</label>
					            <div class="col-md-9">
					                <input type="text" id="example-text-input" name="example-text-input" class="form-control" placeholder="">
					            </div>
					        </div>

					        <div class="form-group">
					            <label class="col-md-3 control-label" for="example-text-input"> <i class="fa fa-user"></i> Destinatario</label>
					            <div class="col-md-9">
					                <input type="text" id="example-text-input" name="example-text-input" class="form-control" placeholder="">
					            </div>
					        </div>

					        <div class="form-group">
					            <label class="col-md-3 control-label" for="example-text-input"> <i class="fa fa-pencil"></i> Descripción</label>
					            <div class="col-md-9">
					                <textarea id="example-textarea-input" name="example-textarea-input" rows="9" class="form-control" placeholder="Descripcion problema.."></textarea>
					            </div>
					        </div>

					        <div class="form-group">
						        <label class="col-md-3 control-label" for="example-file-input"> <i class="fa fa-file"></i> Adjunto</label>
						        <div class="col-md-9">
						            <input type="file" id="example-file-input" name="example-file-input">
						        </div>
						    </div>

							<div class="form-group pull-right">
								<div class="col-sm-12">
									<button type="button" class="btn btn-success">Enviar</button>
								</div>
							</div>
		            	</div>
		       		</div>
	       	</div>
    	</div>
	</div>
</div>


</div>

</div>
