        <form action="<?php print $this->url->get('ajax/reiterarTicket') ?>" class="form-horizontal" data-type="ajax" method="post">
        <div class="modal-dialog " style="width: 70%">
        <div class="modal-content">
            <!-- Updates Title -->
            <div class="block-title" style=" margin: 0px;">
                <button type="button" class="close closeModal" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2><strong>Insistir Ticket <?php echo $tck;?> </strong></h2>
            </div>
            <!-- END Updates Title -->
            <div class="modal-body">
                <!-- Resultado -->      
                <div class="stp-trat"  id="stp-trat-resultado">
                    <div class="form-group row text-center " style="margin-top: -15px;">
                        <div class="col-lg-12">
                            <h3><strong>Ingresar detalle de la Insistencia</strong></h3> <br>
                        </div>
                        <div class="col-lg-6 center-block">
                           <textarea id="txt" name="txt" rows="5" class="form-control push-bit" placeholder="descripción"></textarea>
                        </div>
                        <div class="col-lg-6 center-block">

                            <input type="hidden" value="<?php print($tck) ?>" name="tck">
                            
                            <input type="submit" value="Reiterar"  style="width:100%" class="btn btn-bc">
                        </div>                                               
                    </div>
                </div>                                                                                          
            </div>

        
            <div class="modal-footer">
                <div class="btn-group btn-group-sm pull-right">
                    <a class="btn btn-sm btn-default pull-right" data-dismiss="modal" href=""> Cerrar</a>
                </div>
            </div>
        </div>
    </div>
    </form>