<h4 id="helptitle">Seleccione tipo de solicitud</h4>

<div class="row strap nsBoton-tecnologia defaultClass">
	<div class="col-md-3 text-center ">
		<a href="javascript:void(0)" class="widget active widget-hover-effect1 nsBoton modal-catalogo-op primera-opcion " data-val="Aplicaciones de Negocio" data-next="aplicaciones" data-type="segundaVista" ><i class="fa fa-suitcase fa-5x"></i>
            <div class="widget-simple text-center catalogo-op-desc">
                <h3 class="widget-content text-center" >
                 <strong>Aplicaciones de Negocio</strong><br>
                </h3>
          		<span >Habilitar accesos mediante configuración de permisos, solución de problemas o recuperar datos.</span>      
            </div>
    	</a>
	</div>	
	<div class="col-md-3 text-center">
		<a href="javascript:void(0)" class="widget active widget-hover-effect1 nsBoton modal-catalogo-op primera-opcion" data-next="form-solicitudes" data-val="Comunicaciones y Mensajería" data-type="segundaVista"><i class="fa fa-commenting-o fa-5x"></i>
            <div class="widget-simple text-center catalogo-op-desc">
                <h3 class="widget-content text-center " >
                 <strong>Comunicaciones y Mensajería</strong><br>
                </h3>
                <span >Habilitar accesos a redes wifi, telefonía Lync o solución de problemas comunicacionales.</span>
            </div>
    	</a>
	</div>	
	<div class="col-md-3 text-center">
		<a href="javascript:void(0)" class="widget active widget-hover-effect1 nsBoton modal-catalogo-op primera-opcion" data-next="form-solicitudes" data-val="Correo Electrónico y Calendarios" data-type="segundaVista" ><i class="fa fa-envelope fa-5x"></i>
            <div class="widget-simple text-center catalogo-op-desc">
                <h3 class="widget-content text-center " >
                 <strong>Correo Electrónico y Calendarios</strong><br>
                </h3>
                <span >Recuperar buzón de mensajes, habilitar correo encriptado o solución de problemas relacionados.</span>
            </div>
    	</a>
	</div>											
	<div class="col-md-3 text-center">
		<a href="javascript:void(0)" class="widget active widget-hover-effect1 nsBoton modal-catalogo-op primera-opcion" data-next="form-solicitudes" data-val="Cuentas y Accesos" data-type="segundaVista"><i class="fa fa-users fa-5x"></i>
            <div class="widget-simple text-center catalogo-op-desc">
                <h3 class="widget-content text-center " >
                 <strong>Cuentas y Accesos</strong><br>
                </h3>
                <span >Crear cuentas, habilitar accesos y permisos a usuarios o solución de problemas relacionados.</span>
            </div>
    	</a>
	</div>	
</div>