<div id="modal-encuesta" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" style="padding-right: 0px !important;">
    <div class="modal-dialog" style="width: 90%;">
    	<div class="modal-content">
    		<div class="modal-header" style="padding: 15px;">
    			<button type="button" style="color:white;" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    			<h3 class="modal-title" id="myModalLabel">Encuesta de Satisfacción de Servicios
    			</h3>
    		</div>
    		<div class="modal-body item" style="min-height:70vh;">
    	    	<form action="" method="post">
    	    	<div class="row">
    	                <div class="col-lg-12 center-block text-center" style="margin-bottom: 15px;">
    	                    <h4>Ayúdenos a mejorar nuestro servicio, califique en la siguiente encuesta el servicio recibido a través de la Mesa de Servicios <?php print $idTicket ?></h4>
    	                </div>

    	                <div class="col-lg-8 center-block text-center" style="margin-bottom: 15px;">
                            <div class="row">
                                <div class="col-lg-12">
                                    <label class="control-label" style="font-size: 18px;" for="scsl_cdg">¿Ha quedado conforme con la solución?:</label>
                                </div>
                                <div class="col-lg-12" style="text-align: center;">
                                    <div class="like-selector">
                                        <input <?php print $like==1?'checked="checked"':''; ?> class="hidden" id="option1" name="preg0" type="radio" value="1" />
                                        <label for="option1" id="preg01" class="<?php print $like==1?'likeimg':'likeimgGray'; ?>"></label>
                                        <input  <?php print $like==2?'checked="checked"':''; ?> class="hidden" id="option2" name="preg0" type="radio" value="2" />
                                        <label for="option2" id="preg02" class="<?php print $like==2?'dislikeimg':'dislikeimgGray'; ?>"></label>
                                    </div>
                                </div>
                            </div>
    	                </div>

    	                 <div class="col-lg-12 center-block">
    	                 	<div class="table-responsive">
                                <table class="table table-bc table-striped table-vcenter table-encuesta">
                                    <thead>
                                        <tr class="thead-encuesta">
                                            <th width="2%">Nº</th>
                                            <th width="44%">PREGUNTA</th>
                                            <th width="10%" class="text-center">Muy Insatisfecho</th>
                                            <th width="10%" class="text-center">Insatisfecho</th>
                                            <th width="10%" class="text-center">Neutro</th>
                                            <th width="10%" class="text-center">Satisfecho</th>
                                            <th width="11%" class="text-center">Muy Satisfecho</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr class="table-encuesta-label">
                                            <td></td>
                                            <td></td>
                                            <td class="label-red"></td>
                                            <td class="label-orange"></td>
                                            <td class="label-yellow"></td>
                                            <td class="label-green"></td>
                                            <td class="label-greenb"></td>
                                        </tr>
                                        <tr class="radio-custom">
                                        	<td>1</td>
                                        	<td>Califique en general el servicio entregado por el Centro de Servicios</td>
                                        	<td class="text-center">
                                        		<input type="radio" name="PREG1" value="1"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG1" value="2"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG1" value="3"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG1" value="4"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG1" value="5"/>
        									</td>
                                        </tr>
                                        <tr class="radio-custom">
                                        	<td>2</td>
                                        	<td>Califique la facilidad para acceder o comunicarse con nuestros ejecutivos</td>
                                        	<td class="text-center">
                                        		<input type="radio" name="PREG2" value="1" />
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG2" value="2"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG2" value="3"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG2" value="4"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG2" value="5"/>
        									</td>
                                        </tr>
                                       <tr class="radio-custom">
                                        	<td>3</td>
                                        	<td>Califiquela actitud del ejecutivo, es decir, disposición y amabilidad</td>
                                        	<td class="text-center">
                                        		<input type="radio" name="PREG3" value="1"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG3" value="2"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG3" value="3"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG3" value="4"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG3" value="5"/>
        									</td>
                                        </tr>
                                        <tr class="radio-custom">
                                        	<td>4</td>
                                        	<td>Califique el tiempo total de resolución del motivo que provocó su llamado</td>
                                        	<td class="text-center">
                                        		<input type="radio" name="PREG4" value="1"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG4" value="2"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG4" value="3"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG4" value="4"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG4" value="5"/>
        									</td>
                                        </tr>
                                        <tr class="radio-custom">
                                        	<td>5</td>
                                        	<td>Califique la calidad de la solución entregada en relación al motivo de su llamada</td>
                                        	<td class="text-center">
                                        		<input type="radio" name="PREG5" value="1"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG5" value="2"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG5" value="3"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG5" value="4"/>
        									</td>
        									<td class="text-center">
                                        		<input type="radio" name="PREG5" value="5"/>
        									</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
    	                </div>
    	                <div class="col-lg-6 center-block">
    	                   <textarea id="comentarios" name="comentarios" rows="3" class="form-control push-bit" placeholder="Comentarios Adicionales"></textarea>
    	                </div>
    	                <div class="col-lg-3 center-block" style="margin-top: 30px;">
    	                   <button style="width:100%" type="button" class="btn btn-bc">Enviar Evaluación</button>
    	                </div> 
    	            </div>
                    <input type="text" class="hidden" name="idTicket" value="<?php print $idTicket ?>" />                                              
    	         </form>                                                                                         
    		</div>
    		<div class="modal-footer">
    			<button type="button" class="btn btn-default btn-bc" data-dismiss="modal">Cerrar</button>
    		</div>
    	</div>
    </div>
</div>