    <!-- BREADCRUMBS -->
    <div  class="header-pages">
        <div id="modal_header_1">
            <h3 class="modal-title_1"> Módulo de <strong> Preguntas Frecuentes, Procedimientos, Formularios e Instructivos.</strong></h3>
        </div>
        <div id="breadcrumbs">
            <span class="bcTecnologia nsMenu">
                <a class="bc-text" href="<?php print($this->url->get("comercio"))?>"><span id="textTecnologia">Inicio</span></a>
            </span>
            <span class="bcTecnologia nsMenu">
                <i class="fa fa-arrow-right"></i>   
                <a class="bc-text" href="<?php print($this->url->get("comercio"))?>/conocimiento"><span id="textTecnologia">Preguntas Frecuentes, Procedimientos, Formularios e Instructivos.</span></a>
            </span>  
            <span class="bcTecnologia nsMenu">
                <i class="fa fa-arrow-right"></i>   
                <span id="textTecnologia">Documento</span>
            </span>                            
        </div>

    </div>
    <!-- ./BREADCRUMBS -->


    <div class="row">
        <div class="col-md-10 center-block">
<?php if($pcData == null){ ?>
            <div class="block full">
                <!-- View Message Title -->
                <div class="block-title">
                    <div class="block-options pull-right">
                        
                    </div>
                    <h2><strong>Error en el proceso de busqueda Intentelo nuevamente</strong> </h2>
                </div>
			</div>
<?php }else{ ?>
            <div class="block full">
                <!-- View Message Title -->
                <div class="block-title">
                    <div class="block-options pull-right">
                        
                    </div>
                    <h2><strong><?php print($pcData['titulo'])?></strong> </h2>
                </div>
                <!-- END View Message Title -->

                <!-- Message Meta -->
                <table class="table table-borderless table-vcenter remove-margin">
                    <tbody>
                        <tr>
                            <td class="text-right"><strong><?php print($pcData['fecha_formateada'])?></strong></td>
                        </tr>
                    </tbody>
                </table>
                <hr>
                <!-- END Message Meta -->

                <!-- Message Body -->
				<p><?php print(implode('</p><p>',explode('<br />
<br />', nl2br($pcData['texto']))))?></p>
                <hr>
                <!-- END Message Body -->

                <!-- Attachments Row -->
                <div class="row block-section">
                <h4 style="padding: 10px;"> Adjuntos</h4>
				<?php foreach($pcData['adjunto'] as $item){
				?>
                    <div class="col-xs-4 col-sm-2 text-center">
                        <a href="<?php print($item['href']);?>" target="_blank">
                            <i class="fi fi-<?php $ext=explode('.',$item['name']);print(end($ext));?> fa-4x push-bit"></i>
                        </a>
                        <span class="text-muted"><?php print($item['name']);?></span>
                    </div>
				<?php }?>
                </div>
                <!-- END Attachments Row -->

            </div>
<?php }?>


        </div>
    </div>