    <!-- BREADCRUMBS -->
    <div  class="header-pages">
        <div id="modal_header_1">
            <h3 class="modal-title_1"> Consultar <strong> Solicitudes</strong></h3>
        </div>
        <div id="breadcrumbs">
            <span class="bcTecnologia nsMenu">
                <a class="bc-text" href="<?php print($this->url->get("comercio"))?>"><span id="textTecnologia">Inicio</span></a>
            </span>
            <span class="bcTecnologia nsMenu">
                <i class="fa fa-arrow-right"></i>   
                <span id="textTecnologia">Solicitudes</span>
            </span>                            
        </div>

    </div>
    <!-- ./BREADCRUMBS -->


				 <!-- Tickets List -->
                    <div class="block full">
                        <div class="block-content-full">
                            <div class="table-responsive remove-margin-bottom">
                                
                                <table id="table" class="table table-striped table-vcenter  table-condensed remove-margin-bottom">
                                    <thead>
                                        <tr>
                                            <th width="20%" class="text-center">Nº Ticket</th>
                                            <th width="10%">Estado</th>
                                            <th>Descripción Breve</th>
                                            <th width="20%" class="text-center">Evaluar Ticket    </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <!--<tr>
                                            <td data-pagina="1" class="text-center bc-text"><a href="<?php print($this->url->get('ticket')) ?>" >#TCK420</a></td>
                                            <td><span class="label label-pendiente">PENDIENTE</span></td>
                                            <td>
                                                Necesito cambiar contraseña usuario SSO<br>
                                                <span class="text-muted">7/03/2016 <strong> 16:40 </strong></span>
                                            </td>
                                            <td class="text-center bc-text"> </td>
                                        </tr>-->
                                        
                                            <?php 
                                                $i = 1;
                                                foreach ($pcData['tckList'] as $key => $val) 
                                                {
                                                    $page = ceil($i / 10);
                                                    ?>
                                                    <tr id="fila-<?php echo $val['CallID']; ?>">
                                                        <td class="text-center bc-text">
                                                            <?php  
                                                            $label = "bc";
                                                            if ($val['Status'] == 'Aceptado' or (strpos($val['Status'], 'Abierto') !== false)) {
                                                                $label = "encurso";
                                                            }
                                                            else if(strpos($val['Status'], 'Pendiente') !== false)
                                                            {
                                                                 $label = "pendiente";
                                                            } else if(strpos($val['Status'], 'Rechazado') !== false)
                                                            {
                                                                 $label = "rechazado";
                                                            }
                                                            else if(strpos($val['Status'], 'Cerrado') !== false)
                                                            {
                                                                 $label = "cerrado";
                                                            }
                                                            //cerrado, rechazado y bc 
                                                            ?>
                                                            <a id="<?php echo 'verTicket'.$val['CallID']; ?>" href="#" class="bc-text" data-id="<?php echo $val['CallID']; ?>"><?php echo $val['CallID']; ?></a>
                                                            
                                                        </td>
                                                    <td><span class="label label-<?php echo $label; ?>"><?php echo $val['Status']; ?></span></td>
                                                    <td><?php echo $val['Title']; ?></td>
                                                    <?php if(strpos($val['Status'], 'errado')) {?>
                                                    <td class="padding0center"><div class="like-selector" data-toggle="popoverhover" data-placement="top" title="" data-content="Haz clic en uno de estos iconos para evaluar el servicio" class="fa fa-check-square-o" data-original-title="¡Evaluar Atención!">
                                                            <input class="hidden" id="like<?php echo $val['CallID']; ?>1" name="conf-<?php echo $val['CallID']; ?>" type="radio" value="1" data-id="<?php echo $val['CallID']; ?>" />
                                                            <label for="like<?php echo $val['CallID']; ?>1" class="likeimgGray"></label>
                                                            <input class="hidden" id="like<?php echo $val['CallID']; ?>2" name="conf-<?php echo $val['CallID']; ?>" type="radio" value="2" data-id="<?php echo $val['CallID']; ?>" />
                                                            <label for="like<?php echo $val['CallID']; ?>2" class="dislikeimgGray"></label>
                                                        </div></td>
                                                        <?php } else{ ?>
                                                        <td class="padding0center">
                                                            <div class="like-selector">
                                                                <label></label>
                                                            </div>
                                                        </td>
                                                        <?php } ?>
                                                    </tr>
                                                    <?php
                                                    $i = $i + 1;
                                                }
                                             ?>

                                    </tbody>
                                </table>
                            <form id="verTicketForm" action="<?php print $this->url->get('comercio/ticket') ?>" method="post">
                                <input class="hidden" name="id" id="idTicket">
                            </form>
                            <form id="evaluacionForm" action="<?php print $this->url->get('comercio/evaluarAtencionModal') ?>" method="post" enctype="multipart/form-data" data-type="ajax">
                                <input  class="hidden" id="optionLike" name="optionLike" />
                                <input  class="hidden" id="ticketId" name="ticketId" />
                            </form>
                            </div>
                        
                        </div>
                    </div>
                    <!-- END Tickets List -->


<div id="contenidomodal">
    
</div>


