<div class="modal-dialog" style="width: 90%;">
	<div class="modal-content">
		<div class="modal-header" style="padding: 15px;">
			<button type="button" style="color:white;" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h2 class="modal-title" id="myModalLabel">Encuesta de Satisfacción de Servicios

			</h2>
		</div>
		<div class="modal-body item" style="min-height:75vh;">
	    	<form action="" method="post">
	    	<div class="row">
	                <div class="col-lg-12 center-block text-center" style="padding-bottom: 20px;">
	                    <h4>Ayúdenos a mejorar nuestro servicio, califique en la siguiente encuesta el servicio recibido a través de la Mesa de Servicios</h4>
	                </div>

	                <div class="col-lg-8 center-block" style="padding-bottom: 30px;">
	                	<div class="row">
	                		<label class="col-sm-6 control-label" style="font-size: 16px;" for="scsl_cdg"><i class="fa fa-check"></i>¿Ha quedado conforme con la solución?:</label>
	                		<div class="col-sm-6" >
								<ul class="like">
									<li>
									    <input type="radio" id="a25" class="like" name="conforme" value="1" />
									    <label for="a25"><img id="likeimg" src="<?php print($this->url->get("img/like-11.png"))?>"></label>
									</li>
									<li>
									    <input type="radio" id="a50" class="like" name="conforme" value="2" />
									    <label for="a50"><img id="dislikeimg" src="<?php print($this->url->get("img/like-22.png"))?>"></label>
									</li>
								</ul>
							</div>
						</div>
	                </div>

	                 <div class="col-lg-12 center-block">
	                 	<div class="table-responsive">
                            <table class="table table-bc table-striped table-vcenter">
                                <thead>
                                    <tr style="background-color: #006598; line-height: 30px; font-size: 14px; color:white;">
                                        <th width="5%">Nº</th>
                                        <th widget="40%">PREGUNTA</th>
                                        <th class="text-center">Muy Insatisfecho</th>
                                        <th class="text-center">Insatisfecho</th>
                                        <th class="text-center">Neutro</th>
                                        <th class="text-center">Satisfecho</th>
                                        <th class="text-center">Muy Satisfecho</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                    	<td>1</td>
                                    	<td>Califique en general el servicio entregado por el Centro de Servicios</td>
                                    	<td class="text-center">
                                    		<input type="radio" name="PREG1" value="1"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG1" value="2"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG1" value="3"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG1" value="4"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG1" value="5"/>
    									</td>
                                    </tr>
                                    <tr>
                                    	<td>2</td>
                                    	<td>Califique la facilidad para acceder o comunicarse con nuestros ejecutivos</td>
                                    	<td class="text-center">
                                    		<input type="radio" name="PREG2" value="1" />
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG2" value="2"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG2" value="3"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG2" value="4"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG2" value="5"/>
    									</td>
                                    </tr>
                                    <tr>
                                    	<td>3</td>
                                    	<td>Califiquela actitud del ejecutivo, es decir, disposición y amabilidad</td>
                                    	<td class="text-center">
                                    		<input type="radio" name="PREG3" value="1"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG3" value="2"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG3" value="3"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG3" value="4"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG3" value="5"/>
    									</td>
                                    </tr>
                                    <tr>
                                    	<td>4</td>
                                    	<td>Califique el tiempo total de resolución del motivo que provocó su llamado</td>
                                    	<td class="text-center">
                                    		<input type="radio" name="PREG4" value="1"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG4" value="2"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG4" value="3"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG4" value="4"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG4" value="5"/>
    									</td>
                                    </tr>
                                    <tr>
                                    	<td>5</td>
                                    	<td>Califique la calidad de la solución entregada en relación al motivo de su llamada</td>
                                    	<td class="text-center">
                                    		<input type="radio" name="PREG5" value="1"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG5" value="2"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG5" value="3"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG5" value="4"/>
    									</td>
    									<td class="text-center">
                                    		<input type="radio" name="PREG5" value="5"/>
    									</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
	                </div>
	                <div class="col-lg-6 center-block">
	                   <textarea id="comentarios" name="comentarios" rows="3" class="form-control push-bit" placeholder="Comentarios Adicionales"></textarea>
	                </div>
	                <div class="col-lg-6 center-block">
	                   <button style="width:100%" type="button" class="btn btn-bc">Enviar Evaluación</button>
	                </div> 
	            </div>                                              
	         </form>                                                                                         
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default btn-bc" data-dismiss="modal">Cerrar</button>
		</div>
	</div>
</div>