<form id="solicitudForm" action="<?php print $this->url->get('comercio/CreateInteraction') ?>" method="post" enctype="multipart/form-data">
<div class="nsBoton-form-solicitudes strap">
		<div class="row">
			<div class="col-md-8 center-block" style="text-align: center; padding-bottom: 15px;">
				<h4><div class="alert" style="color:white ;background-color: #002453;border-color: #002453;">Datos <strong>Solicitud</strong></div></h4>
			</div>

			
			<div class="col-md-8 center-block">
			
			<?php if($pcData['campos']['detinatario']) {?>
			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<label class="col-md-4 control-label" for="scsl_cdg">
								<i class="fa fa-user">&nbsp;&nbsp;</i> <strong style="color:red;">*</strong> Destinatario:</label>
							<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Destinatario" data-content="Persona a la que se le entregará el servicio.">
								<select  data-placeholder="Selecciona un Opción"  id="input-select_dest" name="select_dest" class="select-chosen">
									<?php 
										foreach ($pcData['contactos'] as $key => $value) { ?>
											<option value="<?php echo $value; ?>" <?php if(strcmp($this->auth->getName(), $value) == 0){echo ' selected';} ?>><?php echo $value; ?></option>
									<?php	
										}
									 ?>
		                        </select>
		                        <label id="alert-select_dest" style="color:red; display: none;" >Campo requerido</label>
							</div>
						</div>
					</div>
					</div>
			</fieldset>
			<?php } 
			if($pcData['campos']['ci']) {?>
			<br>
			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
						<label class="col-md-4 control-label" for="select_sa">
							<i class="fa fa-cog">&nbsp;&nbsp;</i> <strong style="color:red;">*</strong> Servicio Afectado:</label>
						<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Servicio Afectado" data-content="Blah Blah">
							<select data-placeholder="Selecciona un Opción"  id="input-select_sa" name="select_sa" class="select-chosen">
                                <option value=""></option>
                                <?php foreach ($pcData['listas'] as $key => $value) {?>
                                	<option value="<?php print $key ?>"><?php print $key ?></option>
                                <?php } ?>
	                        </select>
	                        <label id="alert-select_sa" style="color:red; display: none;" >Campo requerido</label>
						</div>
						</div>
					</div>
				</div>	 						
			</fieldset>
			<br>
			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
						<label class="col-md-4 control-label" for="scsl_cdg">
							<i class="fa fa-cogs">&nbsp;&nbsp;</i> <strong style="color:red;">*</strong> Componente:</label>
						<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Componente" data-content="Componente de Tecnología (Sistema, Hardware, Software)">
							<select data-placeholder="Selecciona un Opción"  id="input-select_ci" name="select_ci" class="select-chosen">
                                <option value=""></option>
	                        </select>
	                        <label id="alert-select_ci" style="color:red; display: none;" >Campo requerido</label>
						</div>
						</div>
					</div>
				</div>	 						
			</fieldset>
			<?php } 
			if($pcData['campos']['descripcion']) {?>
			<br>

			<fieldset>
				<div class="form-group">
					<label class="col-md-4 control-label" for="horaInicio">
						<i class="fa fa-minus">&nbsp;&nbsp;</i> <strong style="color:red;">*</strong> Descripción Breve:</label>
					<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Descripción Breve" data-content="Blah Blah Blah ..">
						<input type="text" id="input-descripcion_breve" name="title" class="form-control" >
	                        <label id="alert-descripcion_breve" style="color:red; display: none;" >Campo requerido</label>
						<br>
					</div>
				</div>
				<br>
				<div class="form-group">
					<label class="col-md-4 control-label" for="horaFin">
						<i class="fa fa-navicon">&nbsp;&nbsp;</i> <strong style="color:red;">*</strong> Otros Antecedentes:</label>
					<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Otros Antecedentes" data-content="Blah Blah Blah ..">
						<textarea id="input-description" class="form-control" rows="4" cols="50" name="description"></textarea>
	                        <label id="alert-description" style="color:red; display: none;" >Campo requerido</label>
					</div>
				</div>
			</fieldset>
			<?php }
			 if($pcData['campos']['interrupcion']) {?>
			<br>

			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
						<label class="col-md-4 control-label" for="scsl_cdg">
							<i class="fa fa-user">&nbsp;&nbsp;</i> <strong style="color:red;">*</strong> Hay Interrupción de Servicio ?:</label>
						<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Interrupción de Servicio" data-content="Blah Blah Blah ..">
							<select data-placeholder="Selecciona un Opción"  id="input-select_is" name="select_is" class="select-chosen">
                                    <option value="SI">SI</option>
                                    <option selected="selected" value="NO">NO</option>
	                        </select>
	                        <label id="alert-select_is" style="color:red; display: none;" >Campo requerido</label>
						</div>
						</div>
					</div>
				</div>	 						
			</fieldset>
			<?php }
			if($pcData['campos']['impacto']) {?>
			<br>

			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<label class="col-md-4 control-label" for="scsl_cdg">
								<i class="fa fa-line-chart">&nbsp;&nbsp;</i> <strong style="color:red;">*</strong> Impacto:</label>
							<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Impacto" data-content="Blah Blah Blah ..">
								<select data-placeholder="Selecciona un Opción"  id="input-select_i" name="select_i" class="select-chosen">
	                                <option value="4">Empresa</option>
	                                <option value="3">Sitio/Dpto</option>
	                                <option value="2">Varios Usuarios</option>
	                                <option value="1" selected="selected">Usuario</option>
		                        </select>
	                        <label id="alert-select_i" style="color:red; display: none;" >Campo requerido</label>
							</div>
						</div>
					</div>
				</div>
			</fieldset>
			<?php }
			if($pcData['campos']['urgencia']) { ?>
			<br>

			<fieldset>
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
						<label class="col-md-4 control-label" for="scsl_cdg">
						<i class="fa fa-exclamation-circle">&nbsp;&nbsp;</i> <strong style="color:red;">*</strong> Urgencia:</label>
							<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Urgencia" data-content="Blah Blah Blah ..">
								<select data-placeholder="Selecciona un Opción"  id="input-select_u" name="select_u" class="select-chosen">
	                                <option value="1">Crítica</option>
	                                <option value="2">Alta</option>
	                                <option value="3">Media</option>
	                                <option value="4" selected="selected">Baja</option>
		                        </select>
	                        <label id="alert-select_u" style="color:red; display: none;" >Campo requerido</label>
							</div>
						</div>
					</div>
				</div>	 
			</fieldset>
			<?php }
			 if($pcData['campos']['desde']) {?>
			<br>

			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<label class="col-md-4 control-label" for="scsl_cdg"><i class="fa fa-calendar">&nbsp;&nbsp;</i> <strong style="color:red;">*</strong> Desde:</label>
							<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Desde" data-content="Blah Blah Blah ..">
								<input id="input-desde" type="text" class="form-control input-datepicker" name="desde" data-date-format="dd/mm/yyyy" readonly="readonly" style="background-color: white;">
	                        <label id="alert-desde" style="color:red; display: none;" >Campo requerido</label>
							</div>
						</div>
					</div>
				</div>
			</fieldset>
			<?php }
			if($pcData['campos']['hasta']) { ?>
			<br>

			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<label class="col-md-4 control-label" for="scsl_cdg"><i class="fa fa-calendar">&nbsp;&nbsp;</i> <strong style="color:red;">*</strong> Hasta:</label>
							<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Hasta" data-content="Blah Blah Blah ..">
								<input id="input-hasta" type="text" class="form-control input-datepicker" name="hasta" data-date-format="dd/mm/yyyy" readonly="readonly" style="background-color: white;">
	                        <label id="alert-hasta" style="color:red; display: none;" >Campo requerido</label>
							</div>
						</div>
					</div>
				</div>
			</fieldset>
			<?php }
			if($pcData['campos']['autorizacion']) { ?>
			<br>

			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<label class="col-md-4 control-label" for="scsl_cdg">
							</label>	
							<div class="col-md-8">
								<div class="alert alert-warning alert-dismissable">
				                    <i class="fa fa-exclamation-circle"></i> Se requiere adjunte la autorización de su gerencia para procesar la solicitud de servicio
				                </div>
							</div>
						</div>
					</div>
				</div>
			</fieldset>
			<?php } 
			if($pcData['campos']['adjunto']) { ?>
			<br>

			<fieldset>
				<div class="form-group">
	                <label class="col-md-4 control-label" for="example-file-multiple-input">
	                 <?php print($pcData['campos']['autorizacion'] == true? '<strong style="color:red;">*</strong>':''); ?>
	                 	Información Adicional
	                 </label>
	                <div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Información Adicional" data-content="Blah Blah Blah ..">
	                    <input type="file" id="<?php print($pcData['campos']['autorizacion'] == true?'input-':''); ?>file" name="example-file-multiple-input" multiple="">
	                    <!-- info alert required -->
	                    <?php if($pcData['campos']['autorizacion']) { ?>
	                    <label id="alert-file" style="color:red; display: none;" >Campo requerido</label>
	                    <?php } ?>
	                </div>
	            </div>
			</fieldset>

			<?php } ?>
			<fieldset style="margin-top: 30px;">
				<div class="form-group">
					<input type="hidden" name="familia" value="<?php echo $pcData['catalogo']['familia']; ?>">
					<input type="hidden" name="area" value="<?php echo $pcData['catalogo']['area']; ?>">
					<input type="hidden" name="subarea" value="<?php echo $pcData['catalogo']['subarea']; ?>">
					<input type="hidden" name="campo-detinatario" value="<?php echo $pcData['campos']['detinatario']; ?>">
					<input type="hidden" name="campo-ci" value="<?php echo $pcData['campos']['ci']; ?>">
					<input type="hidden" name="campo-titulo" value="<?php echo $pcData['campos']['titulo']; ?>">
					<input type="hidden" name="campo-descripcion" value="<?php echo $pcData['campos']['descripcion']; ?>">
					<input type="hidden" name="campo-desde" value="<?php echo $pcData['campos']['desde']; ?>">
					<input type="hidden" name="campo-impacto" value="<?php echo $pcData['campos']['impacto']; ?>">
					<input type="hidden" name="campo-urgencia" value="<?php echo $pcData['campos']['urgencia']; ?>">
					<input type="hidden" name="campo-interrupcion" value="<?php echo $pcData['campos']['interrupcion']; ?>">
					<input type="hidden" name="campo-autorizacion" value="<?php echo $pcData['campos']['autorizacion']; ?>">
					<input type="hidden" name="campo-adjunto" value="<?php echo $pcData['campos']['adjunto']; ?>">
					<input type="hidden" name="campo-hasta" value="<?php echo $pcData['campos']['hasta']; ?>">
					<div class="" style="margin: 0 auto;width: 200px;">
						<a id="btnGuardar" href="#" class="btn btn-block btn-bc">Enviar Solicitud</a>
					</div>
			  	</div>
			</fieldset>
			</div>
		</div>
	</div>
</form>
