    <!-- BREADCRUMBS -->
    <div  class="header-pages">
        <div id="modal_header_1">
            <h3 class="modal-title_1"> Ticket <?php echo $pcData['tck']->CallID;?></strong></h3>
        </div>
        <div id="breadcrumbs">
            <span class="bcTecnologia nsMenu">
                <a href="<?php print($this->url->get("comercio"))?>"><span id="textTecnologia">Inicio</span></a>
            </span>
            <span class="bcTecnologia nsMenu">
                <i class="fa fa-arrow-right"></i>   
                <span id="textTecnologia">Tickets</span>
            </span>
            <span class="bcTecnologia nsMenu">
                <i class="fa fa-arrow-right"></i>   
                <span id="textTecnologia"><?php echo $pcData['tck']->CallID;?></span>
            </span>                              
        </div>

    </div>
    <!-- ./BREADCRUMBS -->

    <div class="row">
        <div class="col-xs-4 ">
                <!-- Your Plan Widget -->
                <div class="block">
                    <div class="block-title">
                        <h3>
                           <strong>Datos del ticket </strong>
                            
                        </h3>
                        <div class="block-options pull-right">
                            <a href="#modal-reiterar" data-toggle="modal">
                            <span class="label btn-bc"> <i class="gi gi-repeat"></i> Reiterar</span>
                            <!--<span class="label btn-bc"> <i class="gi gi-repeat"></i>Evaluar</span>-->
                            </a>
                        </div>

                    </div>
                    <div class="widget-extra-full catalogo-lista-home">
                        <div class="row ">
                                                                    <!-- Tickets List -->
                            <div class="tab-pane active" id="tickets-list">
                                <div class="block-content-full " style="padding-left:30px;padding-right:30px;">
                                    
                                    <span><i class="gi gi-user"></i> Por <strong><?php echo $pcData['tck']->ReportedByContact;?></strong></span> <br>
                                    <span><i class="gi gi-calendar"></i> Fecha Solicitud: <strong><?php echo $pcData['tck']->OpenTime;?></strong></span><br>
                                    <span><i class="gi gi-ok_2"></i> Categoría: <strong><?php echo $pcData['tck']->Area;?></strong></span><br>
                                    <span><i class="gi gi-ok_2"></i> Sub-Categoría: <strong><?php echo $pcData['tck']->Subarea;?></strong></span><br>
                                    <span><i class="hi hi-send"></i> Estado: <strong><?php echo $pcData['tck']->Status;?></strong></span><br>
                                    <h3><strong><?php echo $pcData['tck']->Title;?></strong></h3><br>
                                    <h5><strong>Descripción: </strong></h5><br>
                                    <?php
                                        foreach ($pcData['tck']->Description as $var) {
                                            echo "<h5>" . $var . "</h5><br>";
                                        }
                                    ?>
                                </div>
                            </div>
                            <!-- END Tickets List -->
                        </div>
                    </div>
                 </div>
                <!-- END Your Plan Widget -->
        </div>

        <div class="col-xs-8 ">
            <!-- Your Plan Widget -->
            <div class="block">
                <div class="block-title">
                    <h3>
                       <strong>Detalle ticket </strong><?php echo $pcData['tck']->CallID;?>
                        
                    </h3>

                </div>
                <div class="widget-extra-full catalogo-lista-home">
                    <div class="row ">
                                                                <!-- Tickets List -->
                        <div class="tab-pane active" id="tickets-list">
                            <div class="block-content-full " style="padding-left:30px;padding-right:30px;">
                               <table class="table table-bordered table-striped table-vcenter">
                                    <tbody>
                                        <tr>
                                            <td class="text-center">Destinatario Servicio</td>
                                            <td > <?php echo $pcData['tck']->ServiceRecipient;?></td>
                                        </tr>
                                        <tr>
                                            <td class="text-center" >C.I. Afectado</td>
                                            <td > <?php echo $pcData['tck']->AffectedCI;?></td>
                                        </tr>
                                        <tr>
                                            <td class="text-center" >Impacto</td>
                                            <td > <?php echo $pcData['tck']->Impact;?></td>
                                        </tr>
                                        <tr>
                                            <td class="text-center" >Urgencia</td>
                                            <td > <?php echo $pcData['tck']->Urgency;?></td>
                                        </tr>
                                         <tr>
                                            <td class="text-center" >Servicio Afectado</td>
                                            <td > <?php echo $pcData['tck']->AffectedService;?></td>
                                        </tr>
                                        <tr>
                                            <td class="text-center" >Última Actualización</td>
                                            <td > <?php echo $pcData['tck']->UpdateTime;?></td>
                                        </tr>
                                       
                                    </tbody>
                                </table>

                            </div>
                        </div>
                        <!-- END Tickets List -->
                    </div>
                </div>
             </div>
            <!-- END Your Plan Widget -->



            <!-- Your Plan Widget -->

            <!-- END Your Plan Widget -->
        </div>
        <div id="modal-reiterar" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog " style="width: 50%; height: 200px;">
                <div class="modal-content">
                    <!-- Updates Title -->
                    <div class="block-title" style=" margin: 0px;">
                        <button type="button" class="close closeModal" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h2><strong>Reiterar Ticket <?php echo $pcData['tck']->CallID;?></strong></h2>
                    </div>
                    <!-- END Updates Title -->
                    <div class="modal-body">
                        <textarea name="txt" id="txt" rows="5" class="form-control" placeholder="Comentario"></textarea>
                        <input type="submit" value="Reiterar"  style="width:100%" class="btn btn-bc">
                    </div>
                </div>
            </div>
        </div>
</div>