                                    <?php
                                        $first = true; 
                                        foreach ($pcData['tck']->trace as $key => $val) { 
                                            if($first)
                                            {
                                    ?>
                                        <tr style="background-color: #F9F9F9;">
                                            <td class="text-center"><strong style="font-size: 14px;"><?php echo $val['fecha']; ?></strong></td>
                                            <td class="text-center"><strong style="font-size: 14px;"><?php echo $val['tipo']; ?></strong></td>
                                            <td class="text-center"><strong style="font-size: 14px;"><?php echo $val['user']; ?></strong></td>
                                            <td><strong style="font-size: 14px;"><?php echo $val['description']; ?></strong></td>
                                        </tr>
                                    <?php 
                                            $first = false;
                                            }
                                            else
                                            {
                                     ?>
                                        <tr>
                                            <td class="text-center"><?php echo $val['fecha']; ?></td>
                                            <td class="text-center"><?php echo $val['tipo']; ?></td>
                                            <td class="text-center"><?php echo $val['user']; ?></td>
                                            <td><?php echo $val['description']; ?></td>
                                        </tr>
                                    <?php } }?>