    <!-- BREADCRUMBS -->
    <div  class="header-pages">
        <div id="modal_header_1">
            <h3 class="modal-title_1"> Ticket #tck123</strong></h3>
        </div>
        <div id="breadcrumbs">
            <span class="bcTecnologia nsMenu">
                <a href="<?php print($this->url->get("comercio"))?>"><span id="textTecnologia">Inicio</span></a>
            </span>
            <span class="bcTecnologia nsMenu">
                <i class="fa fa-arrow-right"></i>   
                <span id="textTecnologia">Tickets</span>
            </span>
            <span class="bcTecnologia nsMenu">
                <i class="fa fa-arrow-right"></i>   
                <span id="textTecnologia">#ticket123</span>
            </span>                              
        </div>

    </div>
    <!-- ./BREADCRUMBS -->

    <div class="row">
        <div class="col-xs-4 ">
                <!-- Your Plan Widget -->
                <div class="block">
                    <div class="block-title">
                        <h3>
                           <strong>Datos del ticket </strong>
                            
                        </h3>
                        <div class="block-options pull-right">
                            <a href="#">
                            <span class="label btn-bc"> <i class="gi gi-repeat"></i> Reiterar</span>
                            <!--<span class="label btn-bc"> <i class="gi gi-repeat"></i>Evaluar</span>-->
                            </a>
                        </div>

                    </div>
                    <div class="widget-extra-full catalogo-lista-home">
                        <div class="row ">
                                                                    <!-- Tickets List -->
                            <div class="tab-pane active" id="tickets-list">
                                <div class="block-content-full " style="padding-left:30px;padding-right:30px;">
                                    
                                    <span><i class="gi gi-user"></i> Por <strong>Alejandro Aguilera</strong></span> <br>
                                    <span><i class="gi gi-calendar"></i> Fecha Solicitud: <strong>27/03/2016</strong></span><br>
                                    <span><i class="gi gi-ok_2"></i> Categoría: <strong>Tecnología</strong></span><br>
                                    <span><i class="hi hi-send"></i> Estado: <strong>PENDIENTE</strong></span><br>
                                    <h3><strong>Necesito activación de mi cuenta</strong></h3><br>
                                    <h5><strong>Descripción: </strong> Mi cuenta no está activada ya que al ingresar los sistemas internos me arroja un error.</h5><br>

                                </div>
                            </div>
                            <!-- END Tickets List -->
                        </div>
                    </div>
                 </div>
                <!-- END Your Plan Widget -->
        </div>

        <div class="col-xs-8 ">
            <!-- Your Plan Widget -->
            <div class="block">
                <div class="block-title">
                    <h3>
                       <strong>Detalle ticket </strong>#TICK123
                        
                    </h3>

                </div>
                <div class="widget-extra-full catalogo-lista-home">
                    <div class="row ">
                                                                <!-- Tickets List -->
                        <div class="tab-pane active" id="tickets-list">
                            <div class="block-content-full " style="padding-left:30px;padding-right:30px;">
                               <table class="table table-bordered table-striped table-vcenter">
                                    <tbody>
                                        <tr>
                                            <td class="text-center">Destinatario Servicio</td>
                                            <td > Alejandro Aguilera</td>
                                        </tr>
                                        <tr>
                                            <td class="text-center" >C.I. Afectado</td>
                                            <td > Item de Configuración</td>
                                        </tr>
                                        <tr>
                                            <td class="text-center" >Impacto</td>
                                            <td > Medio</td>
                                        </tr>
                                        <tr>
                                            <td class="text-center" >Urgencia</td>
                                            <td > Alta</td>
                                        </tr>
                                         <tr>
                                            <td class="text-center" >Interrupción de Servicio</td>
                                            <td > Correo</td>
                                        </tr>
                                        <tr>
                                            <td class="text-center" >Adjunto</td>
                                            <td > SI</td>
                                        </tr>
                                        <tr>
                                            <td class="text-center" >Desde - Hasta</td>
                                            <td > 27/03/2016 - 10/04/2016</td>
                                        </tr>
                                       
                                    </tbody>
                                </table>

                            </div>
                        </div>
                        <!-- END Tickets List -->
                    </div>
                </div>
             </div>
            <!-- END Your Plan Widget -->



            <!-- Your Plan Widget -->

            <!-- END Your Plan Widget -->
        </div>
</div>