<!-- Widgets Row -->
<div class="row">
    <div class="col-md-6 ">
        <!-- Timeline Widget -->
        <div class="widget ">
            <div class="widget-extra themed-background-dark">
                <div class="widget-options">
                </div>
                <h3 class="widget-content-light">
                    Nueva <strong>Solicitud</strong>
                    <small><a href="page_ready_timeline.php"><strong></strong></a></small>
                </h3>
            </div>
            <div class="widget-extra " style="padding-right: 0px; padding-left: 0px;">

		        <!-- Working Tabs Content -->
		        <div class="row row-catalogo catalogo-lista-home">
    				<div class="col-xs-12 text-center">
						<a href="<?php print($this->url->get("comercio/solicitudServicio/sistemas-ti"))?>" class="widget active widget-hover-effect1 catalogo-menu primera-opcion" style="padding: 0px;" data-val="Aplicaciones de Negocio" data-next="aplicaciones" data-type="segundaVista" >
				            <div class="widget-simple text-center">
				            	<div class="row">
				            		<div class="col-xs-4">
				            			<i class="gi gi-display fa-3x"></i>
						                <h3 class="widget-content" >
						                 <strong>Sistemas TI</strong><br>
						                </h3>
					                </div>
					                <div class="col-xs-8">
					                	<div class="description">
					          				<span >Habilitar accesos mediante configuración de permisos, solución de problemas o recuperar datos.</span>
					          			</div>
					          		</div>
				          		</div> 
				            </div>
			        	</a>
					</div>
					<div class="col-xs-12 text-center">
						<a href="<?php print($this->url->get("comercio/solicitudServicio/servicios-ti"))?>" class="widget active widget-hover-effect1 catalogo-menu segunda-opcion" style="padding: 0px;" data-val="Aplicaciones de Negocio" data-next="aplicaciones" data-type="segundaVista" >
				            <div class="widget-simple text-center">
				            	<div class="row">
				            		<div class="col-xs-4">
				            			<i class="gi gi-bullhorn fa-3x"></i>
						                <h3 class="widget-content " >
						                 <strong>Servicios TI</strong><br>
						                </h3>
					                </div>
					                <div class="col-xs-8">
					                	<div class="description">
					          				<span>Habilitar accesos mediante configuración de permisos, solución de problemas o recuperar datos.</span>
					          			</div>
					          		</div>
				          		</div> 
				            </div>
			        	</a>
					</div>
					<div class="col-xs-12 text-center">
						<a href="<?php print($this->url->get("comercio/solicitudServicio/infraestructura"))?>" class="widget active widget-hover-effect1 catalogo-menu tercera-opcion" style="padding: 0px;" data-val="Aplicaciones de Negocio" data-next="aplicaciones" data-type="segundaVista" >
				            <div class="widget-simple text-center">
				            	<div class="row">
				            		<div class="col-xs-4 widget-title-cat">
				            			<i class="gi gi-group fa-3x"></i>
						                <h3 class="widget-content" >
						                 <strong>Infraestructura y Servicios Generales </strong><br>
						                </h3>
					                </div>
					                <div class="col-xs-8">
					                	<div class="description">
					          				<span>Habilitar accesos mediante configuración de permisos, solución de problemas o recuperar datos.</span>
					          			</div>
					          		</div>
				          		</div> 
				            </div>
			        	</a>
					</div>
				</div>	
	        </div>
		        <!-- END Working Tabs Content -->

		</div>
        <!-- Timeline Widget -->

        <!-- Timeline Widget -->
        <div class="widget ">
            <div class="widget-extra themed-background-dark">
                <div class="widget-options">
                </div>
                <h3 class="widget-content-light">
                    Buscar <strong> Documentos </strong>
                    <small><a href="page_ready_timeline.php"><strong></strong></a></small>
                </h3>
            </div>
            <div class="widget-extra " style="padding-right: 0px; padding-left: 0px;">

		        <!-- Working Tabs Content -->
		        <div class="row row-catalogo catalogo-lista-home">
    				<div class="col-xs-12 text-center">
						<a href="<?php print($this->url->get("comercio/conocimiento"))?>" class="widget active widget-hover-effect1 catalogo-menu " style="padding: 0px;" data-val="Aplicaciones de Negocio" data-next="aplicaciones" data-type="segundaVista" >
				            <div class="widget-simple text-center">
				            	<div class="row">
				            		<div class="col-xs-4">
				            			<i class="gi gi-search fa-3x"></i>
						                <h3 class="widget-content" >
						                 <strong>Buscar</strong><br>
						                </h3>
					                </div>
					                <div class="col-xs-8">
					          			<span > Buscar Preguntas Frecuentes, Procedimientos, Formularios e Instructivos.</span>
					          		</div>
				          		</div> 
				            </div>
			        	</a>
					</div>
				</div>	
	        </div>
		        <!-- END Working Tabs Content -->
		</div>
    </div>

    <div class="col-md-6">
        <!-- Your Plan Widget -->
        <div class="widget">
            <div class="widget-extra themed-background-dark">
                <h3 class="widget-content-light">
                   <strong>Consultar</strong> Solicitud 
                    <small><a href="page_ready_pricing_tables.php"><strong></strong></a></small>
                    <small>Ultimos tickets</small>
                   
                </h3>

            </div>
            <div class="widget-extra-full rm-padding-top">
                <div class="row ">
				    <?php if(sizeof($pcData['tckList']) > 0) 
				    	{
				    ?>
				    <!-- Tickets List -->
                    <div class="tab-pane active" id="tickets-list">
                        <div class="block-content-full">
                            <div class="table-responsive remove-margin-bottom table-main">
                            	
                                	<table class="table table-bc table-striped table-vcenter remove-margin-bottom">
	                                    <thead>
	                                        <tr>
	                                            <th class="">ID</th>
	                                            <th>Estado</th>
	                                            <th>Categoria</th>
	                                            <th width="20%"> Evaluar Ticket</th>
	                                        </tr>
	                                    </thead>
	                                    <tbody>
	                                    	<form id="verTicketForm" action="<?php print $this->url->get('comercio/ticket') ?>" method="post">
	                                    	<?php 
	                                    		$i = 0;
	                                    		foreach ($pcData['tckList'] as $key => $val) 
	                                    		{
	                                    			if($i >= 9){
	                                    				break;
	                                    			} ?>
	                                    			<tr>
	                                    				<td class='text-center bc-text'>
			                                    			<?php  
			                                    			$label = "bc";
			                                    			if ($val['Status'] == 'Aceptado' or (strpos($val['Status'], 'Abierto') !== false)) {
															    $label = "encurso";
															}
															else if(strpos($val['Status'], 'Pendiente') !== false)
															{
																 $label = "pendiente";
															} else if(strpos($val['Status'], 'Rechazado') !== false)
															{
																 $label = "rechazado";
															}
															else if(strpos($val['Status'], 'Cerrado') !== false)
															{
																 $label = "cerrado";
															}
															//cerrado, rechazado y bc 
															?>
			                                    			<a id="<?php echo 'verTicket'.$val['CallID']; ?>" href="#" class="bc-text" data-id="<?php echo $val['CallID']; ?>"><?php echo $val['CallID']; ?></a>
			                                    			
	                                    				</td>
	                                    			<td><span class="label label-<?php echo $label; ?>"><?php echo $val['Status']; ?></span></td>
	                                    			<td><?php echo $val['Title']; ?></td>
	                                    			<?php if(strpos($val['Status'], 'errado')) {?>
	                                    			<td class="padding0center"><div class="like-selector" data-toggle="popoverhover" data-placement="top" title="" data-content="Haz clic en uno de estos iconos para evaluar el servicio" class="fa fa-check-square-o" data-original-title="¡Evaluar Atención!">
												        	<input class="hidden" id="like<?php echo $val['CallID']; ?>1" name="conf-<?php echo $val['CallID']; ?>" type="radio" value="1" data-id="<?php echo $val['CallID']; ?>" />
												        	<label for="like<?php echo $val['CallID']; ?>1" class="likeimgGray"></label>
												        	<input class="hidden" id="like<?php echo $val['CallID']; ?>2" name="conf-<?php echo $val['CallID']; ?>" type="radio" value="2" data-id="<?php echo $val['CallID']; ?>" />
												        	<label for="like<?php echo $val['CallID']; ?>2" class="dislikeimgGray"></label>
												    	</div></td>
												    	<?php } else{ ?>
												    	<td></td>
												    	<?php } ?>
	                                    			</tr>
	                                    			<?php
	                                    			$i = $i + 1;
	                                    		}
	                                    	 ?>
	                                    	 	<input class="hidden" name="id" id="idTicket">
	                                        </form>
	                                    </tbody>
	                                </table>


	                            <form id="evaluacionForm" action="<?php print $this->url->get('comercio/evaluarAtencionModal') ?>" method="post" enctype="multipart/form-data" data-type="ajax">
	                                <input  class="hidden" id="optionLike" name="optionLike" />
	                                <input  class="hidden" id="ticketId" name="ticketId" />
	                            </form>

                                <div class="col-md-12 text-center" style="margin-bottom: 6px;">
                                	<a class="bc-text" style="font-size: 16px;" href="<?php print($this->url->get('solicitudes')) ?>"> Ver todos ...</a>
                                </div>
                            </div>
                            <div class="text-center col-xs-12" style="min-height: 73px;padding: 10px;">
                            <br>
                            	<form id="buscarTicketForm" action="<?php print $this->url->get('comercio/ticket') ?>" method="post">
									 <div class="row">
	                            		<div class="col-xs-6">
											 <input type="text" id="id" name="id" class="form-control" placeholder="Nº Ticket" required>
										</div>
										<div class="col-xs-6">
											<button type="submit" style="width:100%" class="btn btn-bc" ><i class="gi gi-search"></i> Buscar Ticket</button>
										</div>
									</div>
								</form>
                            </div>
                        </div>
                    </div>
                    <!-- END Tickets List -->
                    <?php } 
                    	else{
                    ?>
                    	<h3>No se encontraron ticket´s</h3>
                    <?php } ?>
                </div>
            </div>
        </div>
        <!-- END Your Plan Widget -->
    </div>

</div>
<!-- END Widgets Row -->
<div id="contenidomodal">
	
</div>
