<div class="nsBoton-form-solicitudes strap">
		<div class="row" style="margin-top: -20px;">
			<div class="col-md-8 center-block" style="text-align: center; padding-bottom: 15px;">
				<h4><div class="alert" style="color:white ;background-color: #002453;border-color: #002453;">Datos <strong>Solicitud</strong></div></h4>
			</div>

			<div class="col-md-8 center-block">
			<?php if($pcData['campos']['detinatario'] == 'si') {?>
			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<label class="col-md-4 control-label" for="scsl_cdg">
								<i class="fa fa-user">&nbsp;&nbsp;</i>Destinatario:</label>
							<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Destinatario" data-content="Persona a la que se le entregará el servicio.">
								<select  data-placeholder="Selecciona un Opción"  id="select_ci" name="select_ci" class="select-chosen">
									<?php 
										foreach ($pcData['contactos'] as $key => $value) {
											# code...
										}
									 ?>
	                                    <!--<option value="1">Alejandro Aguilera</option>
	                                    <option value="2">Pedro Perez</option>
	                                    <option value="3">Andrés Silvestre</option>
	                                    <option value="4">Fito Osvaldo</option>
	                                    <option value="5">Camilo Cruz</option>
	                                    <option value="6">Héctor Fausto</option>
	                                    <option value="7">María Gualterio</option>
	                                    <option value="8">Osvaldo Edmundo</option>-->
		                        </select>
							</div>
						</div>
					</div>
					</div>
			</fieldset>
			<?php } ?>
			<br>

			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
						<label class="col-md-4 control-label" for="scsl_cdg">
							<i class="fa fa-user">&nbsp;&nbsp;</i>Componente:</label>
						<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Componente" data-content="Componente de Tecnología (Sistema, Hardware, Software)">
							<select data-placeholder="Selecciona un Opción"  id="select_ci" name="select_ci" class="select-chosen">
                                <option value=""></option>
                                <option value="1">Pantallas Digitales</option>
                                <option value="1">Sitio economiamascerca.cl</option>
                                <option value="1">Software Editorial</option>
                                <option value="1">Toweb</option>
                                <option value="1">Sharepoint - Contraloria</option>
                                <option value="1">Base de Datos Cambiarios</option> 
                                <option value="1">Encuestas por Internet</option>
                                <option value="1">Inversiones en el Exterior </option>
                                <option value="1">Otro1</option>
                                <option value="1">Otro2</option>
                                <option value="1">Otro3</option>
	                        </select>
						</div>
						</div>
					</div>
				</div>	 						
			</fieldset>

			<br>

			<fieldset>
				<div class="form-group">
					<label class="col-md-4 control-label" for="horaInicio">
						<i class="fa fa-minus">&nbsp;&nbsp;</i>Descripción Breve:</label>
					<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Descripción Breve" data-content="Blah Blah Blah ..">
						<input type="text" class="form-control" >
						<br>
					</div>
				</div>
				<br>
				<div class="form-group">
					<label class="col-md-4 control-label" for="horaFin">
						<i class="fa fa-navicon">&nbsp;&nbsp;</i>Otros Antecedentes:</label>
					<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Otros Antecedentes" data-content="Blah Blah Blah ..">
						<textarea class="form-control" rows="4" cols="50"></textarea>
					</div>
				</div>
			</fieldset>

			<br>

			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
						<label class="col-md-4 control-label" for="scsl_cdg">
							<i class="fa fa-user">&nbsp;&nbsp;</i>Hay Interrupción de Servicio ?:</label>
						<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Interrupción de Servicio" data-content="Blah Blah Blah ..">
							<select data-placeholder="Selecciona un Opción"  id="select_ci" name="select_ci" class="select-chosen">
                                    <option value="SI">SI</option>
                                    <option selected="selected" value="NO">NO</option>
	                        </select>
						</div>
						</div>
					</div>
				</div>	 						
			</fieldset>

			<br>

			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<label class="col-md-4 control-label" for="scsl_cdg">
								<i class="fa fa-line-chart">&nbsp;&nbsp;</i>Impacto:</label>
							<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Impacto" data-content="Blah Blah Blah ..">
								<select data-placeholder="Selecciona un Opción"  id="select_ci" name="select_ci" class="select-chosen">
	                                <option value="1">Empresa</option>
	                                <option value="2">Sitio/Dpto</option>
	                                <option value="3">Varios Usuarios</option>
	                                <option value="4" selected="selected">Usuario</option>
		                        </select>
							</div>
						</div>
					</div>
				</div>
			</fieldset>

			<br>

			<fieldset>
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
						<label class="col-md-4 control-label" for="scsl_cdg">
						<i class="fa fa-exclamation-circle">&nbsp;&nbsp;</i>Urgencia:</label>
							<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Urgencia" data-content="Blah Blah Blah ..">
								<select data-placeholder="Selecciona un Opción"  id="select_ci" name="select_ci" class="select-chosen">
	                                <option value="1">Crítica</option>
	                                <option value="2">Alta</option>
	                                <option value="3">Media</option>
	                                <option value="4" selected="selected">Baja</option>
		                        </select>
							</div>
						</div>
					</div>
				</div>	 
			</fieldset>

			<br>

			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<label class="col-md-4 control-label" for="scsl_cdg"><i class="fa fa-calendar">&nbsp;&nbsp;</i>Desde:</label>
							<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Desde" data-content="Blah Blah Blah ..">
								<input type="text" class="form-control input-datepicker" data-date-format="dd-mm-yyyy">
							</div>
						</div>
					</div>
				</div>
			</fieldset>

			<br>

			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<label class="col-md-4 control-label" for="scsl_cdg"><i class="fa fa-calendar">&nbsp;&nbsp;</i>Hasta:</label>
							<div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Hasta" data-content="Blah Blah Blah ..">
								<input type="text" class="form-control input-datepicker" data-date-format="dd-mm-yyyy">
							</div>
						</div>
					</div>
				</div>
			</fieldset>

			<br>

			<fieldset>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<label class="col-md-4 control-label" for="scsl_cdg">
							</label>	
							<div class="col-md-8">
							<div class="alert alert-warning alert-dismissable">
			                    <i class="fa fa-exclamation-circle"></i> Se requiere adjunte la autorización de su gerencia para procesar la solicitud de servicio
			                </div>
								
							</div>
						</div>
					</div>
					</div>
			</fieldset>

			<br>

			<fieldset>
				<div class="form-group">
	                <label class="col-md-4 control-label" for="example-file-multiple-input">Información Adicional</label>
	                <div class="col-md-8" data-toggle="popoverhover" data-placement="top" title="Información Adicional" data-content="Blah Blah Blah ..">
	                    <input type="file" id="example-file-multiple-input" name="example-file-multiple-input" multiple="">
	                </div>
	            </div>
			</fieldset>


			<fieldset style="margin-top: 30px;">
				<div class="form-group">
					<div class="col-xs-4 center-block">
						<button id="btnGuardar" type="button" class="btn btn-block btn-bc">Enviar Solicitud</button>
					</div>
			  	</div>
			</fieldset>
			</div>
		</div>
	</div>