    <!-- BREADCRUMBS -->
    <div  class="header-pages">
        <div id="modal_header_1">
            <h3 class="modal-title_1"> Buscar <strong> Preguntas Frecuentes, Procedimientos, Formularios e Instructivos.</strong></h3>
        </div>
        <div id="breadcrumbs">
            <span class="bcTecnologia nsMenu">
                <a class="bc-text" href="<?php print($this->url->get("comercio"))?>"><span id="textTecnologia">Inicio</span></a>
            </span>
            <span class="bcTecnologia nsMenu">
                <i class="fa fa-arrow-right"></i>   
                <span id="textTecnologia">Preguntas Frecuentes, Procedimientos, Formularios e Instructivos.</span>
            </span>                            
        </div>

    </div>
    <!-- ./BREADCRUMBS -->


		<div class="widget ">
		   <div class="widget-extra themed-background-dark">
		  		 <h3 class="widget-content-light">
      	             Búsqueda por Palabras
                    <small><a href=""><strong></strong></a></small>
                </h3>
		   </div>
           <div class="col-lg-12" style="padding: 30px 150px 10px 150px;">
			  <form id="searchForm" action="<?php print($this->url->get('ajax')) ?>/conocimiento" method="post" data-type="ajax">
                 <div class="form-group">
                    <div class="col-md-12">
                        <div class="input-group">
                            <input type="text" id="searchinn" name="searchinn" class="form-control" placeholder="palabras claves a buscar">
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-bc"> <i class="fa fa-search"></i> Buscar</button>
                            </span>
                        </div>
                    </div>
                </div>
		      </form>
            </div>
			<table id="conocimiento-table" class="table table-striped table-vcenter">
				<thead>
					<tr>
						<th><i class="fa fa-briefcase"></i> Resultado Búsqueda</th>
						<th class="text-center hidden-xs" style="width: 20%;">Tiene Adjunto</th>
						<th class="text-center hidden-xs" style="width: 20%;"></th>
						<th class="text-center" style="min-width: 120px; width: 20%;">Acción</th>
					</tr>
				</thead>
				<tbody id="conocimiento-tbody">
                    <?php echo $this->view->render('servicio/servicios_base_conocimiento_tr',array('pcData'=>$pcData));?>
				</tbody>
			</table>			
	    </div>

